### ISSUE TITLE
sync error: EDAMUserException: ENML_VALIDATION parameter=The element type \"br\" must be terminated

### ISSUE THREAD

**Issue by jotech** [robert7/nixnote2#101]
## Expected vs. actual behavior
I cannot  synchronize certain notes because an error occurs about problems with the ``<br>`` tag. To me, the note source looks rather normal. I attached an [example note](https://github.com/robert7/nixnote2/files/3077697/problem.zip) which reproduced the error for me in a fresh database.
```
ERROR 2019-04-14 13:37:46.513 src/communication/communicationmanager.cpp:513 Exception stacktrace:
ERROR 2019-04-14 13:37:46.514 src/communication/communicationerror.cpp:86 "EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=The element type \"br\" must be terminated by the matching end-tag \"</br>\"."
```

## Steps to reproduce the problem

  1. import [example note](https://github.com/robert7/nixnote2/files/3077697/problem.zip)
  2. try synchronize

## Specifications

  - Version: NixNote 2.1.3-bbbf0a1, build at Apr 5 2019 at 08:03:26

**Comment by robert7** [comment]
hmm this is weird
1, I can import the attachment you provided and it really doesn't sync
2, but just do any minimal change - e.g. just add one line and it will sync OK

![screen_20190417_10](https://user-images.githubusercontent.com/1135218/56280211-03a19880-610a-11e9-9f1b-a1c1c2d1a46c.png)

the minimal change will trigger "tidy" which will cleanup the problem
if you just import the note, then tidy is not called, as you import the so called ENML format
editing triggers conversion to HTML and back to ENML 

so I don't know how you produced the note.. what was the origin? is it an old note?

**Comment by jotech** [comment]
ok cool this worked for me to! No I can synchronize again. 
But the cause is unclear to me. I used an older version from march (2.1.3-06fcda9, build at Mar 26 2019).

Maybe it is worth to have a function to trigger tidy for all notes at once? I had the problem that I had to edit ~100 notes because I couldn't sync for two weeks.
Thanks for you help, I appreciate it a lot! :)

**Comment by HaleTom** [comment]
@jotech Did the content on the offending notes come from copy / paste from a web browser?

#98 is a different ENML_VALIDATION burp coming from a copy / pasted note.

**Comment by jotech** [comment]
i can't say where it did come from but for some time all of my changed or created notes were affected. maybe some issue with a former version?

**Comment by robert7** [comment]
>maybe some issue with a former version?

yes. could be. previous versions had more sync issues

>Maybe it is worth to have a function to trigger tidy for all notes at once? I had the problem that I had to edit ~100 notes because I couldn't sync for two weeks.

hmm... normally the cleanup should work stable, so this situation should not be "typical use case". so currently there is no option for "batch tidy"
