### ISSUE TITLE
"Missing Plugin" displayed instead of inline PDF file

### ISSUE THREAD

**Issue by qsman** [robert7/nixnote2#102]
## Expected vs. actual behavior
When viewing note with embedded PDF, I would expect to see the PDF display in the note window. Instead I see the message "missing plugin"

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))

  1.As stated above
[nixnotebebug.txt](https://github.com/robert7/nixnote2/files/3136641/nixnotebebug.txt)

  1.
  1.

## Specifications

Version: 201904050846~2.1.3~ubuntu18.04.1
Linux Mint Tara 19.1
Cinnamon desktop

when running the debug, (aside from the pw errors which I don't know where it comes from, only one account is connected), I see now that it cannot find the corrosponding PDF file in the DB-1 directory. However that PDF does appear in both the Web and Evernote client versions so I don;t know why this was not replicated locally. I have uninstalled/reinstalled nixnote2
[nixnotebebug.txt](https://github.com/robert7/nixnote2/files/3136665/nixnotebebug.txt)
[nixnotebebug.txt](https://github.com/robert7/nixnote2/files/3136666/nixnotebebug.txt)

**Comment by robert7** [comment]
Sorry no idea...
The log file just says the PDF file was not found, where it was expected. Looks like corrupted data directory.

To I suggest try a new "sync" from scratch.
You can do this by starting nixnote with new data & config directory.
E.g. `nixnote2 --configDir=$HOME/.nixnote2-test`
This will create new config/data dir in $HOME/.nixnote2-test, then you need to login, wait for full sync and hopefully all will work.

More info in: https://github.com/robert7/nixnote2/wiki/Relocation-of-config-and-data-directory

if it will work, then you can find out where the current data & config directory is, then delete it & re-sync.

**Comment by qsman** [comment]
Robert,

You have ESP.I was just working on this earlier!

This time around:
 1) I uninstalled Nixnote
2) uninstalled Qt5 seperately as  it was still in the menu
3)  searched and deleted ALL Nixnote references on my partition including
Trash
4) then reinstalled from the Ubuntu repository.

Now it works perfectly.

You can close this issue out - maybe add to the troubleshooting to make
sure that the Qt5/4 is also gone. I appreciate your responses!

Thanks,

Nachum Hurvitz
*"Like stars across the sky, we were born to shine"* - Andrea Bocelli

**Comment by robert7** [comment]
ok I updated https://github.com/robert7/nixnote2/wiki/HowTo---What-to-do-if-the-app-crashes
although here each case is a bit different
thx for info
