### ISSUE TITLE
No Shortcuts on Left Hand Panel or Icon Menu

### ISSUE THREAD

**Issue by RyanRix** [robert7/nixnote2#103]
First of all - great work on this project. I'm so glad it hasn't died - it is very useful.

I'm running Version: 201903260817~2.1.3~ubuntu19.04.1 from the develop branch. I switched from stable as I found this issue but develop is the same.

Essentially, there are entries in the 'Shortcuts' section, either at the top of the left-hand panel, or in the icon menu. The similar icon menu entry 'Recently updated' displays several entries - the 'Shortcuts' entry shows nothing, even though I have several set-up.

**Comment by robert7** [comment]
Not sure what you mean... could you post some screenshoots maybe?
Here is how the shortcuts work on my test account - on 201903260816~2.1.3~ubuntu18.04.1

![screen_20190510_03](https://user-images.githubusercontent.com/1135218/57540264-a08fd400-734c-11e9-899d-8a6f1d52b471.png)

**Comment by RyanRix** [comment]
Sure.

Version is: Version: 201905171401~2.1.4-b~ubuntu19.04.1

Evernote Web:
![Screenshot-20190518085539-221x357](https://user-images.githubusercontent.com/49094556/57966531-14cd0780-794b-11e9-8141-d96b98437bd6.png)

with shortcuts.

None show on NixNote2:

![Screenshot-20190518085638-312x268](https://user-images.githubusercontent.com/49094556/57966536-29a99b00-794b-11e9-91ad-63cf9784f699.png)

Clicking on Shortcuts makes no difference. There are none shown on the Icon menu either, though Recently updated does show relevant notes.

I have a workaround, using a tag: ##Shortcut which is then referenced in a saved search, but this only works for notes, not tags or notebooks.

**Comment by RyanRix** [comment]
So, I went to the last resort - I read the manual. 

And it says:

"Favorites
Favorites in NixNote works much the same way as Evernote's windows client. Dragging a note, notebook, tag, or saved search to the favorites menu allows for quicker access to those notes.

Please note that favorites are not synchronized across clients. Evernote has not yet provided an API interface to permit this."

And this works. Dragging the required notes to the Shortcuts menu item makes them shortcuts. They also appear on the icon menu. They do not appear to sync, which is a shame, but is also the expected behavior. 

Please feel free to close this 'bug' and thanks for all your work.

**Comment by robert7** [comment]
Exactly... the shortcuts don'tt sync, because there is not Evernote API for that.
So shortcuts in Nixnote are local to Nixnote.
