### ISSUE TITLE
Adding NixNote v2.0.2 UserDocumentation.pdf content to the wiki

### ISSUE THREAD

**Issue by nopivnick** [robert7/nixnote2#11]
@robert7 

[as promised](https://github.com/baumgarr/nixnote2/issues/446#issuecomment-411153832), I've pulled the content from @baumgarr 's NixNote version 2.0.2 User's Guide and Technical Manual, formatted it in Markdown, and dumped it in a wiki page on your repo.

I figured it would be helpful to re-purpose @baumgarr 's excellent documentation but I'm not sure what the etiquette is here as far as attribution, acknowledgment, etc..

stuff I did:

* format the content in Markdown
* limit the Table Of Contents to H1 only
* fixed a few typos

stuff I didn't do:

* change @baumgarr 's narrative (historical narrative, first person narrative)
* check for any content that may no longer apply given your work thus far on v2.1

I think there are some changes to the layout in certain sections that might make for easier reading but that's probably better addressed once you figure out how you plan to incorporate the content.

I didn't bother forking the Wiki, just added a New Page through the web GUI. the page is [here](https://github.com/robert7/nixnote2/wiki/_NixNote-v2.0.2-UserDocumentation.pdf) but it doesn't seem to be showing up in pane on the right that lists Wiki content, perhaps because I prefixed the title with an underscore or perhaps because you need to approve the addition.

fwiw.

**Comment by robert7** [comment]
OK thx!

I'll will add some intro and check why the page isn't displayed. don't edit it for now.
Regarding attribution i'll add some intro/explanation at beginning of the text. Otherwise its OK to use it (as its [GPL](https://www.gnu.org/licenses/gpl-3.0.en.html) and we stay here with GPL).

**Comment by robert7** [comment]
note: ...as I renamed the page, you aren't anymore listed as author :) ou may do few more edits, so your name is displayed..

but as there is git underneath the wiki, your contribution is forever there anyway..

![screen_20180825_02](https://user-images.githubusercontent.com/1135218/44620444-ac0d9e80-a894-11e8-9b3d-f5d524450e5a.png)

**Comment by nopivnick** [comment]
> I was skeptical about simply dumping all the old content in the new wiki

there's so much good information and it's really well organized but it's a lot for one wiki page, to be sure.

> I'll think about what to do with it later.

you might want to cannibalize it over time, pulling out one section at a time, checking it for any changes / updates that need to be made, and moving it to it's own wiki page. that would cull it down and make things easier to find as far as using the wiki.

**Comment by nopivnick** [comment]
I'm happy to help with the above, I just figured it would be best to start with one block of content and have you weigh-in.

**Comment by robert7** [comment]
OK & i'll try to move the "legacy docs" to a subdirectory. There you can divide in parts, so they can be better indexed and referenced. I think updating/removing unrelevant/obsolete text isn't neccessary - i'll just add remarks marked with "v2.1+" to the parts where the legacy docs isn't valid anymore. And such remards can be added later, when the app changes further.

**Comment by robert7** [comment]
..I looked up and it seems that folders in [github wiki aren't reasonably supported](https://stackoverflow.com/questions/11088285/github-wiki-directories) (can't be used for namespacing)..

So I let the file where it is. You may move ahead with dividing it to subpages. But as **all** pages in wiki need to have unique names, then pls use some prefix. Like I did with "[FAQ's](https://github.com/robert7/nixnote2/wiki/FAQ)". I suggest "Legacy: " prefix. Like "Legacy: Evernote and NixNote Overview" .. "Legacy: NixNote History" ...

**Comment by robert7** [comment]
I did extract the first 2 chapters. I'm not sure if the "Legacy" prefix is the best, but let start with that. Later this can be changed eventually..
