### ISSUE TITLE
Pasted links no longer hyperlink

### ISSUE THREAD

**Issue by msbentley** [robert7/nixnote2#113]
## Expected vs. actual behavior

When pasting a URL into NixNote2, it should (and used to) automatically generated a hyperlink,

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))

  1. Copy a link to the clipboard
  2. Paste the link into NN2

## Specifications

  - Version: 201906041316~2.1.4-c~ubuntu18.04.1

**Comment by robert7** [comment]
Sorry but you need to post more details.. I'm using this function daily of course and it works obviously.
There could be some special cases where it doesn't work (as the original code is a quite dirty).
So I need to know, in which case it doesn't work for you..

![screen_20190621_01](https://user-images.githubusercontent.com/1135218/59904174-26e70d80-9403-11e9-93ce-b4f5053e6941.png)

As you see .. normal case works without problem.

**Comment by msbentley** [comment]
Thanks! For me the change is recent (it used to work until ~a week or so) and has stopped working for every single link, even very simple ones. I am using version Version: 201906041316~2.1.4-c~ubuntu18.04.1.

Let me know what other information I can provide!

**Comment by robert7** [comment]
Pls retry with the version 2.1.4-g
should be available soon in develop branch (also in PPA) https://github.com/robert7/nixnote2/releases/tag/continuous-develop

in case you still find a case, where it doesn't work, then pls post a log with DEBUG level

in case you insert more than one url in plain text format, then it is inserted as plain text

**Comment by msbentley** [comment]
Great, this works fine in 2.1.4-g - many thanks!

**Comment by robert7** [comment]
great.
pls use 2.1.4-h, as I did today few more fixes (e.g. paste everno app link dis not worked in 2.1.4-g)
