### ISSUE TITLE
Invalid theme

### ISSUE THREAD

**Issue by Luvideria** [robert7/nixnote2#118]
I am trying to get my gtk theme into the app.
I saw the other issues on the topic and followed the instructions there

https://github.com/baumgarr/nixnote2/issues/469
https://github.com/baumgarr/nixnote2/issues/320
https://github.com/robert7/nixnote2/issues/109
https://github.com/robert7/nixnote2/issues/21
https://github.com/robert7/nixnote2/wiki/NixNote-Themes
https://www.linuxuprising.com/2018/05/get-qt5-apps-to-use-native-gtk-style-in.html

## Expected vs. actual behavior
the theme is not displaying correctly, it is still the default

Themes are all the same except for the background of the editor as pointed out in a previous issue, but there is nothing wrong with my gtk themett as other qt app render it well. Maybe the issue is with the qt version?

What I tried:

- copy theme.ini from repo to ~/.nixnote2 I indeed see the new themes but they just change the background color

- add export QT_QPA_PLATFORMTHEME=gtk2 -> receive following error message in the shell, and it's not launching

`❯ nixnote2 
QApplication: invalid style override passed, ignoring it.
    Available styles: bb10dark, bb10bright, kvantum-dark, kvantum, cleanlooks, gtk2, cde, motif, plastique, qt5ct-style, Windows, Fusion
Cannot mix incompatible Qt library (version 0x50c02) with this library (version 0x50d00)
Aborted (core dumped)`
- add export QT_QPA_PLATFORMTHEME=qt5ct 

`❯ nixnote2 
qt5ct: using qt5ct plugin
QApplication: invalid style override passed, ignoring it.
    Available styles: bb10dark, bb10bright, kvantum-dark, kvantum, cleanlooks, gtk2, cde, motif, plastique, qt5ct-style, Windows, Fusion
INFO  2019-07-03 20:55:49.687 src/utilities/crossmemorymapper.cpp:59 Shared memory segment allocated, instance key: "71f36554-0b95-476f-8f09-500097af58e72"
INFO  2019-07-03 20:55:49.688 src/main.cpp:287 NixNote 2.1.4-c-4b984203, build at Jul  3 2019 at 18:26:55, with Qt 5.13.0 running on 5.13.0
INFO  2019-07-03 20:55:49.689 src/main.cpp:290 To get more detailed startup logging use --logLevel=1
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: no`
-  I tried first the version nixnote2 from the AUR
-  I tried first the version nixnote2 from the AUR
- Then this version https://aur.archlinux.org/packages/nixnote2-git/
- my .gtkrc-2.0 has been edited with gtk-theme-name=theme name

## Specifications
- nixnote: Version: 2.1.4-c-4b984203
- Qt version 5.13.0
- my gtk theme https://www.gnome-look.org/p/1246387/

**Comment by robert7** [comment]
You need someway force Qt into dark mode. Then Nixnote will run in dark mode.
I'm not able to help you with your specific distribution setup.

So it more a question how to configure Qt on your particular system, then question related to Nixnote.
