### ISSUE TITLE
nixnote2 window vanishes on move to another workspace

### ISSUE THREAD

**Issue by jjon** [robert7/nixnote2#119]
Recent convert to linux, though I've used \*nix for a long time. I've used Mac for the convenience of its UI, until it got less and less convenient. So, I got a project76 Galago Pro with their Ubuntu/PopOS and I'm now trying to make the migration. One big sticking point is that I've got years worth of notes in DevonThink. The Evernote client for linux, nixnote2, looks like a good candidate for a replacement. I have a notion that since I can save DevonThink folders, and notes as html, I ought to be able to write a script to translate the result into .nnex and import it into nixnote2. That's the goal anyway.

But first things first. My immediate problem is to get nixnote2 to work reliably with workspaces. This problem may well be due to my inexperience in linux, but looks a lot like bug.
    
    NixNote2 Version: 2.1.2-1 installed via popos's PopShop.
    Pop!_OS 19.04 64-bit
    Processor: Intel® Core™ i5-8265U CPU @ 1.60GHz × 8
    GNOME 3.32.2

Here's some behavior I can't explain:
----
Clicking on the icon in the applications bar often starts it up and a new window is created maximized (sometimes it takes two or more clicks). If I then try to move the window to any other workspace, it simply disappears. But `ps` shows me that the process is still running.

Weirder still: if I've got, say, sublimetext open in a workspace and startup nixnote2. And then I move **sublimetext** to another workspace, I'm left with nixnote2 window alone in this workspace. Well and good, but then if I activate any other workspace, the nixnote2 window disappears. And, `ps` tells me the process is still present:
```
me@pop-os:~$ ps -fC nixnote2
UID        PID  PPID  C STIME TTY          TIME CMD
me        9931     1  0 Jul04 ?        00:00:18 /usr/bin/nixnote2

```

I can start up nixnote2 from the command line and it invariably tells me this:
```
me@pop-os:~/Desktop$ nixnote2
	WARN  2019-07-04 16:01:04.276 src/utilities/crossmemorymapper.cpp:55 Shared memory segment failed to allocate, instance key: "4f8d7aff-838e-457f-b452-cf585604144a1"
	WARN  2019-07-04 16:01:04.276 src/utilities/crossmemorymapper.cpp:55 Shared memory segment failed to allocate, instance key: "4f8d7aff-838e-457f-b452-cf585604144a1"
	INFO  2019-07-04 16:01:04.276 src/main.cpp:225 New shared memory segment could not be created.
	INFO  2019-07-04 16:01:04.276 src/main.cpp:226 We assume another instance with the same configuration is running, instance key:"4f8d7aff-838e-457f-b452-cf585604144a1"
	INFO  2019-07-04 16:01:04.276 src/main.cpp:252 Another running instance with same account detected - configured action: "SHOW_OTHER" instance key:"4f8d7aff-838e-457f-b452-cf585604144a1"
	INFO  2019-07-04 16:01:04.276 src/main.cpp:257 Trying to activate it..
```
If anyone has some diagnostic hints or suggestions, I'd be grateful.

Jon

**Comment by robert7** [comment]
Hmm.. to be honest I don't know.
I don't use workspaces.
Did you try the AppImage version? Try the "normal one" (with Qt 5.5) and you can also try the experimental build with Qt 5.11 ( https://github.com/robert7/nixnote2/releases/download/v2.1.3/NixNote2-qt511-x86_64.AppImage )

I have no idea wha NIxNote should vanish if you don't minimize or "restore" it.
The restore code is a bit wild... to cover all case whenever NN ist restored from systray or just minimized etc. All relevant functions are in nixnote.cpp (restoreAndShowMainWindow(), showMainWindow
If you a able to recompile the code, you could try to modify this 2 methods to see if it makes any difference.
One potentialy questionable call is "setWindowFlags(Qt::WindowStaysOnTopHint)" which I use to restore window from minimized/minimized to tray.

"Another running instance with same account detected - configured action: "SHOW_OTHER" ..." means that the nixnote is really running in background and the current instance is trying to activate the other.
For me it works quite well...

**Comment by jjon** [comment]
Here's some further information that might prove diagnostic:

I was evaluating nixnote, in part, because it looked as though it could serve as a local stand-alone note-taking application in addition to being an Evernote client. So I was working in a nixnote user account that had no corresponding Evernote account. I had therein no trouble adding and manipulating notes, but, of course, they were not synced to an Evernote account. This was just what I wanted, except for the window/workspace behaviour described above. But, when I switched to the user account that **was** synced to an Evernote account, that behaviour went away and the window persists when moved to another workspace, as expected.

So, it appears that the unfortunate workspace behaviour applies only to unsynced nixnote accounts.

**Comment by skhadem** [comment]
I have same behavior on Ubuntu 18.04 with a synced account, trying to switch workspaces with nixnote open causes it to close and slows my whole system down for a few seconds

**Comment by robert7** [comment]
OK. I'll try to look at it later

**Comment by robert7** [comment]
I did try with Ubuntu 18.04
It seems Nixnote really disappears when switching the workspaces...
But all methods I use to display it will display it instantly
1. "Show" from systray
2. trying to start it again
3. global key shortcut (I have Super-N) - https://github.com/robert7/nixnote2/wiki/System-wide-global-keyboard-shortcuts

So... yes .. its kind of glitch... but there is very easy workaround to display nixnote again


![screen_20190724_01](https://user-images.githubusercontent.com/1135218/61795676-461ef380-ae24-11e9-8231-51f6682b1b3f.png)


>So, it appears that the unfortunate workspace behaviour applies only to unsynced nixnote accounts.

I think using Nixnote with unsynced accounts has anyway a little sense..
