### ISSUE TITLE
[feature] difference of repos after force resync of remote, 

### ISSUE THREAD

**Issue by timoc** [robert7/nixnote2#12]
If i have an issue where it crashes before/during sync. I would like to be able to find the differences between a forced revert/resync and the broken repo. so something like
```
mv ~/nixnote ~/nixnote-broken
nixnote2 --syncAndExit
nixnote2 --diff ~/nixnote ~/nixnote-broken
```
This way i can gaurentee that i have not lost data or similarily corrupted my remote evernote repo

**Comment by robert7** [comment]
If fixed the problem with command line.
So the sync from command line **now works for me** (syntax: `nixnote21 sync`).
The version with `--syncAndExit` still crashes; i did n't even knew, there are 2 different ways how to start sync (I'll look at it later).

If think the requested feature is not realistic to implement => won'tFix :)

But the sync should already be **quite stable**.

1. "corrupted my remote evernote repo" - Evernote does a quite strong validation -  this should be VERY unlikely
2. "have not lost data" - if the note isn't shown't as "dirty", then you can be quite sure, that your changes landed in cloud (where they should be safe whatever is on your localhost)
3. "nixnote-broken" this should not happen anyway!! :)

The fix in command line is in "beta-3a" - temporarily you can find it at https://www.dropbox.com/sh/bropykm64u8zdmv/AABmCL47YtUXglFMRnTFNnfia?dl=0

**Comment by robert7** [comment]
I removed `--syncAndExit` in beta-3b as it was redundant.

**Comment by robert7** [comment]
I'm closing this; as the problem sync from command line is fixed; and the diff is not realistic to implement (and should not be needed).
