### ISSUE TITLE
SSL error while logging in

### ISSUE THREAD

**Issue by lockie** [robert7/nixnote2#120]
Hey. While working perfectly on my Linux Mint laptop, NixNote2 fails to log in to Evernote on the Gentoo box. 

## Expected vs. actual behavior
Expected: logging in Evernote.
Actual: in login window I see the following:
> Error while reading: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init
> Failed to load URL https://www.evernote.com/OAuth.action.
> QtNetwork Error 99

## Steps to reproduce the problem
[Log file](https://github.com/robert7/nixnote2/files/3395515/messages.log.zip)

  1. Start NixNote and hit "Synchronize" button.
  2. Type in email and then a password. Hit Enter.
  3. The error message appears. Sometimes I can't even type a password. Sometimes the login window just hangs and is painted in background color.

## Specifications
Version: 2.1.3

**Comment by lockie** [comment]
I've just noticed that the error message also appears when in login form I click right mouse button and hit "Reload" menu item (just the URL is different, now it is https://www.evernote.com//OAuth.action?oauth_token=baumgarr-3523.16BF9653187.6E6E6F61757468.82866E474C9E2D65D85B87EB6E66F3B7 )

**Comment by lockie** [comment]
Oh wow, I've tried the AppImage version from releases and both of them (regular and qt511) does not manifest the problem. I think this might me NixNote Gentoo ebuild problem (or even Gentoo Qt packaging problem).
I'll leave the issue open though, just in case.

**Comment by robert7** [comment]
Yes. If the AppImage works, but "normal build" doesn't then its either problem with build or with your local libraries (AppImage has libraries bundled in).
So I can't do anything with this.

**Comment by vlig** [comment]
Hello! The same problem but stable AppImage also doesn't work. I deleted folders ~/.{config,local/share}/nixnote2 and tried again with no luck. Login screen just appears empty for a second, than app crushing. Arch Linux up to date.
[AppImage-messages.log](https://github.com/robert7/nixnote2/files/3489992/AppImage-messages.log)

**Comment by robert7** [comment]
@vlig unfortunately the log only shows "Segmentation fault (core dumped)" without any more info.

The last thing you could try, to be sure you run with clean config/data directory, is something like `nixnote2.AppImage --configDir=$HOME/.nixnote2new` (this will create new config directory in $HOME/.nixnote2new).

**Comment by vlig** [comment]
No. It's definitely doesn't want to work. If I can give some more information someway, please let me know.

**Comment by robert7** [comment]
@vlig unfortunately no idea, you may want to try on different computer
it should be something related to your local setup

**Comment by denis-isaev** [comment]
Same problem.
Somehow I was able to login after authorization on web version in browser.
