### ISSUE TITLE
NO_PUBKEY when using the PPA on Debian 10

### ISSUE THREAD

**Issue by ryanpcmcquen** [robert7/nixnote2#121]
Thanks for keeping nixnote alive!

## Expected vs. actual behavior

PUBKEY would be provided so PPA would function properly on Debian 10.

It cannot be found though.

## Steps to reproduce the problem

  1. Add the PPA on Debian 10.
  2. Install the package.
  3. Observe install output.

```
Err:6 http://ppa.launchpad.net/nixnote/nixnote2-stable/ubuntu eoan InRelease                
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9A66B34BAF11ADDE
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net/nixnote/nixnote2-stable/ubuntu eoan InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9A66B34BAF11ADDE
E: The repository 'http://ppa.launchpad.net/nixnote/nixnote2-stable/ubuntu eoan InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Also, it seems the Debian 10 version is lagging behind at 2.1.2?

## Specifications

  - 2.1.2

**Comment by robert7** [comment]
Hi, 
Im not using debian.. so I'm not sure and I can't test. But I did quick googling and found

https://unix.stackexchange.com/questions/75807/no-public-key-available-on-apt-get-update?noredirect=1&lq=1
and
https://unix.stackexchange.com/questions/452060/apt-update-no-pubkey

you could try:
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9A66B34BAF11ADDE`

Stable PPA (nixnote2-stable  ) is at version: 2.1.4-c
The oficial Debian package seems to be https://packages.debian.org/buster/nixnote2 which is currently "2.1.2-1"

**Comment by ryanpcmcquen** [comment]
@robert7, thank you, that fixed that error, now I have a new one:

```
$ sudo apt-get install nixnote2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nixnote2 : Depends: libqt5core5a (>= 5.12.2) but 5.11.3+dfsg1-1 is to be installed
            Depends: libqt5widgets5 (>= 5.12.2) but 5.11.3+dfsg1-1 is to be installed
            Recommends: mimetex but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Looks like Buster has older deps than the newest version requires. Version 2.1.2 is your version though, correct? I can just roll with that (or try the AppImage).

**Comment by robert7** [comment]
I would recommend:

1. remove the nixnote2 PPA
2. uninstall nixnote2 package (if has been already installed)
3. try to install the official debian package (2.1.2); it could be that the Ubuntu PPA version is not compatible with Debian 10 

AppImage should work out of the box as it doesn't need to be installed has (almost) no dependencies.

The AppImage is newest version - you can select "stable" (continuous build) of "development"

**Comment by ryanpcmcquen** [comment]
Going to try out the included Debian version for now, thanks!
