### ISSUE TITLE
Wiki Update when porting old nixnote2 baumgarr version

### ISSUE THREAD

**Issue by bakshinder** [robert7/nixnote2#123]
Due to several open bugs in 2.0.2 I recently came to know about your active fork of the project. Great Effort indeed! Much appreciation deserved.

But due to my already bulky database of notes in older version I was apprehensive of losing all the contents when updating or reinstalling to 2.1.3

Could you please update the Wiki regarding this I am sure there are many facing these issues.
The porting is smooth without backup database required. 

Just one issue remains when in 2.1.3 version unsynced notes of previous version still face same error but gets resolved when cutting-repasting content back into notes.

## Specifications
Ubuntu 18.04.2 LTS
  - [Version] NixNote 2.02

**Comment by robert7** [comment]
Actually I don't understand what exactly do you mean, as there is a wiki page which describes the "migration" from 2.0 to 2.1 - https://github.com/robert7/nixnote2/wiki/Migration-v2.0-to-v2.1

In fact you shouldn't be needed to do anything.. (I updated the migration page a bit now).

Pls specify more exactly, what are you missing..

**Comment by robert7** [comment]
>Just one issue remains when in 2.1.3 version unsynced notes of previous version still face same error but gets resolved when cutting-repasting content back into notes.

Yes, that's how it works currently (and I don't plan to change it). It result from the behavior that, the "HTML cleanup" is executed after the note is modified. Therefore if you have notes with invalid markup from 2.0 and edit them in 2.1 - mostly the markup will be fixed.You can also do cut/paste as you written..
