### ISSUE TITLE
Recent sync issues

### ISSUE THREAD

**Issue by msbentley** [robert7/nixnote2#125]
In the last approximately one week I've started to see some sync issues with NN2. Originally I was getting repeated requests to re-authorise (every few hours). Eventually I decided to start with a clean sync, and things have run OK so far, but now I have reached a point where if NN2 starts, I get a bunch of:

```
DEBUG 2019-08-22 17:41:45.784 src/qevercloud/QEverCloud/src/http.cpp:139 QEverCloud.http.simpleDownload starting loop, url="https://www.evernote.com/edam/note/s3"
DEBUG 2019-08-22 17:41:46.091 src/qevercloud/QEverCloud/src/http.cpp:147 QEverCloud.http.simpleDownload, url="https://www.evernote.com/edam/note/s3", http code 200, 307 ms
DEBUG 2019-08-22 17:41:46.091 src/qevercloud/QEverCloud/src/http.cpp:139 QEverCloud.http.simpleDownload starting loop, url="https://www.evernote.com/edam/note/s3"
DEBUG 2019-08-22 17:42:16.897 src/qevercloud/QEverCloud/src/http.cpp:147 QEverCloud.http.simpleDownload, url="https://www.evernote.com/edam/note/s3", http code 0, 30806 ms
WARN  2019-08-22 17:42:16.897 src/qevercloud/QEverCloud/src/http.cpp:153 QEverCloud.http.simpleDownload error "Connection timeout."
```
messages, before a timeout. In fact, I repeatably get 20 successful calls before the the timeout. Did something change in the sync logic? Is this Evernote locking the client out for some reason? Other EN clients are working fine right now.

Any hints welcome, and if you  need more info, please let me know!

I'm on ubuntu 18.04 and NixNote: Version: 201908091717~ 2.1.5-a~ ubuntu18.04.1

Thanks!

Markl

**Comment by robert7** [comment]
Hi @msbentley 
yes, this could be side effect of a change in "2.1.5-a". 
Please use the last stable version "2.1.4" to do the first full sync.
I need to recheck that..

I updated the QEvercloud in 2.1.5-a to latest development version (to fix another connection problem), but it could be this makes trouble in full sync.

**Comment by msbentley** [comment]
Thanks @robert7 - I rolled back to 2.1.4, and hit a different type of sync error at the same point. Eventually I worked out that it was an issue with a shared notebook (I think, perhaps, the original owner delete their account or something strange). I deleted that from the web client and the sync seems to be running OK now, so I'll close this issue!

**Comment by robert7** [comment]
@msbentley 
In the version 2.1.5-a I basically added a network timeout of 30 seconds. Some of you requests took longer than that (from your log file 30806 ms).. 
This can be due to slower network or maybe slower reaction of Evernote backend.
Anyway I increased timeout to 4 minutes in 2.1.5-b. This should be enough hopefully.

The previous versions also did have timeout, but it did not worked, so it behaved as "no timeout". Timeout is helpful in situations where network is not stable, as without timeout, the sync may get stuck.

pls. retest with 2.1.5-b

**Comment by msbentley** [comment]
I have only just upgraded to this version, having had to suffer Evernote's "upload limit jail" after trying to work around the previous issues (which seems to be related to shared notebooks). So far so good (but I think the original problem was already fixed by messing with the shared notebooks).
