### ISSUE TITLE
fcitx support in AppImage builds

### ISSUE THREAD

**Issue by Nriver** [robert7/nixnote2#126]
The AppImages for NinNote2 does not support fcitx which I use to input Chinese.  

I tried to unpack the AppImage and find an interesting thing that If I keep the AppImage unpacked and run NixNote2.desktop directly, fcitx would work. If I pack it back, fcitx does not work.

Then I try to add libfcitxplatforminputcontextplugin.so from somewhere else to squashfs-root/usr/plugins/platforminputcontexts/ folder and repack the AppImage, but it did not work. Maybe my .so file comes from a different version of qt which is not compatible with the AppImage.  

My system is Manjaro and the AppImage I use is 2.1.3.

By the way, the AUR version of 2.1.4 works fine with fcitx, so I guess there is some way to get the AppImage version work.

**Comment by robert7** [comment]
hi,
as I don't use chinese, I don't have much possibilities to work on this (I also don't have time, this is another problem :) ).

As I read, you already have your workaround... simply unpack the AppImage and if this works, you have your good to go..

The AUR version uses system libraries, this could be reason why it works.

Another this you may try (if you didn't already) is to try the experimental AppImage build with qt 5.11.
The 2.1.4 version with qt 5.11 is available here: https://github.com/robert7/nixnote2/releases/download/v2.1.4/NixNote2-qt511-x86_64.AppImage
This could work or it could have the same problem.
