### ISSUE TITLE
data loss after sync problems

### ISSUE THREAD

**Issue by jotech** [robert7/nixnote2#127]
In the past, it happened to me two times that my wifi connection got bad while I was synchronizing. The synchronization process got somehow stuck (took more than an hour although I only had minor text changes) and after some time I had to just close nixnote to shutdown my computer.
After starting nixnote again when internet connection was fine, the synchronization worked as expected. But I realized that some ``tags`` got corrupted! An tag labeled _unknown_ appeared in the list. This may not be a big problem in the first place, but in my case an important tag was lost by this and round about 50 notes, which used this tag, lost it and therefore their category and order. Another time, I lost several tags and couldn't figure out which one I lost. In my case, tags are crucial to connect and find notes.
That's why I'm asking, is it possible to more secure the synchronization so that a bad connection cannot cause data loss?

**Comment by robert7** [comment]
Hi,
In the version up to 2.1.4 the timeout for "connection lost" during sync did not really worked. So it could happen that the sync got stuck (solution is simply restart the client).
In the version 2.1.5-a the timeout was 30 second - which worked fine, but could be too less mainly in the initial full sync.
From version 2.1.5-b the timeout works and it is set to 4 minutes. So at least after 4 minutes the sync should stop with fail. Then you can restart (after your network is OK).

Regarding "data loss" - I never experienced that full note would be lost. It noticed few times that the sync of the tags may not be 100% perfect. But from my experience this only happens occasionally really seldom. I have no idea where search for the problem and with the time I have (not) available for this project, its for me not realistic to fix.

I mostly don't use tags as I found it is easier to create good name for the note (put the words I want to use for search in the title), then simply search..

**Comment by jotech** [comment]
Thank you for your feedback and advice! I think it append with 2.1.4. I'm working with 2.1.5 now and will follow how it works out now.
I agree with you that note title is more essential, but in some cases categories/tags are useful especially to associate not yet connected notes. I think the evernote (web) search may also uses tags.
I could completely understand if it's too much work to fix.

**Comment by robert7** [comment]
@jotech normally sync of the tags should work and nothing should be lost.
It can be some edge cases where it is not 100%. 
If you get in situation where some tags on local version are not same as in cloud, you can delete the local version (backup it first) and the do a full sync.
