### ISSUE TITLE
Sync error: see log for details (both AppImages)

### ISSUE THREAD

**Issue by wizonesolutions** [robert7/nixnote2#128]
## Expected vs. actual behavior

When clicking the sync button, notes should sync. Instead, a sync error occurs. I have tried with both 2.1.4 AppImages. I am on Manjaro KDE 18.0.4.

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))

  1. Open app.
  1. Click sync button.

Note: This was with my existing DB from Ubuntu, symlinked from that partition. It might be that I need to reinitialize the entire DB, but I wanted to check first...

[logs-1.tar.gz](https://github.com/robert7/nixnote2/files/3563803/logs-1.tar.gz)

**Comment by robert7** [comment]
Hi
you should be able to copy the data from one system to another - so this should not be problem (if the data aren't corrupted for some reason).

Unfortunately the log you posted, doesn't contain any sync error - so I have no idea what problem you have. The log file is overwritten after restart of Nixnote. So you need to reproduce the sync error, then post the log file with the error.

Here is some hints what to do if you get "weird problems" https://github.com/robert7/nixnote2/wiki/HowTo---What-to-do-if-the-app-crashes

**Comment by wizonesolutions** [comment]
It was something with the actual content of the notes. When I sync first using the official Evernote app, it seems to resolve the issue somehow. Not sure what's going on, but NixNote2's working now!

**Comment by robert7** [comment]
perfect. glad to hear it
