### ISSUE TITLE
Note List is gone when in Narrow note list

### ISSUE THREAD

**Issue by alfianhanafi** [robert7/nixnote2#129]
It only happen when note list view set to **Narrow note list**
![Bug  NixNote 2 1 note list dissapear in Narrow Note list](https://user-images.githubusercontent.com/54639904/64122590-48ce1a80-cdcc-11e9-9b75-291eb1a2791f.gif)

**Comment by robert7** [comment]
Ok - I think actually the list it not "gone", but you have the width of the title set too big, so it just scrolled..
Correct the width of the title column and you should be fine..

![screen_20190906_01](https://user-images.githubusercontent.com/1135218/64429579-9e4d4480-d0b6-11e9-9c6a-f7774d296b1a.png)

**Comment by alfianhanafi** [comment]
thanks for the reply, i think it's not the width of title column.
Because when i change width of title it's still "gone" or "scrolled"

**Actually, when i uncheck date updated or date created it fixed**

![Nixnote2 1 narrow list first solution](https://user-images.githubusercontent.com/54639904/64475130-b604f580-d1a8-11e9-8590-133944331198.gif)

**Comment by robert7** [comment]
You can also reproduce if all shown columns fit in narrow note list width?

**Comment by alfianhanafi** [comment]
> You can also reproduce if all shown columns fit in narrow note list width?

Yeah, absolutely. 
so i think it's bugged when title and date are combined

btw im using Elementary OS 5 Juno based on Ubuntu 18.04 LTS
![NixNote2 1 width is fine](https://user-images.githubusercontent.com/54639904/65005872-96e63080-d92b-11e9-9039-176008897342.gif)

**Comment by robert7** [comment]
sorry no idea... I can't reproduce
