### ISSUE TITLE
Missing attachments can be fixed one  by one - how to fix all?

### ISSUE THREAD

**Issue by lubobde** [robert7/nixnote2#133]
What happens:
Sometimes an attachment does not get replicated into Nixnote. This happens with images as well as with pdf files.

However, this does  not  happen silently. For images I get a missing image icon, for pdfs I get a pdf icon but the file shows size 0kb. I have no idea when this happens and how to replicate it, sorry. Sync does not help as for Nixnote the note is already synced and therefore Nixnote won't touch it anymore.

However, I have figured out how to fix this: I open Note history, select "current copy on Evernote", check the box "replace current note" and off it goes.

This works actually quite well but it is a lot of work.

Is there a way I can apply such an enforced sync or import to all notes at once ?
 
Running Version: 201908091717~2.1.4 on ubuntu 18.04.1

**Comment by robert7** [comment]
>Is there a way I can apply such an enforced sync or import to all notes at once ?

no. but it should not happen. for sure not regularly
what you can try is simply to delete all the local data (backup it first) and do a initial sync. this should fix it. Where the data directory is located on your system: see Help menu.
