### ISSUE TITLE
Add ability to change default code block text

### ISSUE THREAD

**Issue by austinhoag** [robert7/nixnote2#135]
## Expected vs. actual behavior

The default text displayed inside a code block upon creation is: "Insert your code here." I create lots of these blocks daily and I have to delete this text on every one of them before I can enter my code. It would be ideal if I could change the default text to be absent. This would allow the default to be there still unless someone explicitly wants to change it. I am running version: `201910160846~2.1.5~ubuntu16.04.1`

**Comment by robert7** [comment]
I removed the default text, as this is really useless
its available from version 2.1.6-rc2 (available as development build)

**Comment by austinhoag** [comment]
Great, thanks.
