### ISSUE TITLE
Trigger code block with "```" 

### ISSUE THREAD

**Issue by austinhoag** [robert7/nixnote2#136]
To conform with Evernote desktop and other markdown-supported apps, it would be great to be able to trigger a code block with three left single quotes "`" followed by enter.

**Comment by robert7** [comment]
I agree this would be nice... pull request welcome..

But at least I added default keyboard shortcut (Ctrl+Shift+L) same as in Evernote Windows client.
Available from version 2.1.6-rc2

So you can press Ctrl-Shift-L to insert code block.
