### ISSUE TITLE
"EDAMUserException[BAD_DATA_FORMAT]: EDAMUserException: BAD_DATA_FORMAT parameter=authenticationToken"

### ISSUE THREAD

**Issue by gseaborn** [robert7/nixnote2#140]
Since I have upgraded my system to Fedora 30, I am no longer able to synchronize; I get the following errors in /var/log/messages

Nov 13 12:38:44 gseaborn kwin_x11[2720]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 48826, resource id: 69206098, major code: 19 (DeleteProperty), minor code: 0
Nov 13 12:38:44 gseaborn kwin_x11[2720]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 48836, resource id: 69206098, major code: 19 (DeleteProperty), minor code: 0
Nov 13 12:38:44 gseaborn kwin_x11[2720]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 48837, resource id: 69206098, major code: 18 (ChangeProperty), minor code: 0
Nov 13 12:38:44 gseaborn kwin_x11[2720]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 48838, resource id: 69206098, major code: 19 (DeleteProperty), minor code: 0
Nov 13 12:38:44 gseaborn kwin_x11[2720]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 48839, resource id: 69206098, major code: 19 (DeleteProperty), minor code: 0
Nov 13 12:38:44 gseaborn kwin_x11[2720]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 48840, resource id: 69206098, major code: 19 (DeleteProperty), minor code: 0
Nov 13 12:38:44 gseaborn kwin_x11[2720]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 48841, resource id: 69206098, major code: 7 (ReparentWindow), minor code: 0
Nov 13 12:38:44 gseaborn kwin_x11[2720]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 48842, resource id: 69206098, major code: 6 (ChangeSaveSet), minor code: 0
Nov 13 12:38:44 gseaborn kwin_x11[2720]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 48843, resource id: 69206098, major code: 2 (ChangeWindowAttributes), minor code: 0
Nov 13 12:38:44 gseaborn kwin_x11[2720]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 48844, resource id: 69206098, major code: 10 (UnmapWindow), minor code: 0

I have also seen the following errors, usually before the above error, but am not sure whether they are related:

Nov 13 12:36:28 gseaborn plasmashell[2773]: file:///usr/lib64/qt5/qml/QtQuick/Controls/ScrollView.qml:362: TypeError: Type error
Nov 13 12:36:28 gseaborn plasmashell[2773]: file:///usr/lib64/qt5/qml/QtQuick/Controls/ScrollView.qml:363: TypeError: Type error
Nov 13 12:36:28 gseaborn plasmashell[2773]: file:///usr/lib64/qt5/qml/QtQuick/Controls/ScrollView.qml:364: TypeError: Type error
Nov 13 12:36:28 gseaborn plasmashell[2773]: file:///usr/lib64/qt5/qml/QtQuick/Controls/ScrollView.qml:365: TypeError: Type error
Nov 13 12:36:28 gseaborn plasmashell[2773]: file:///usr/lib64/qt5/qml/QtQuick/Controls/Button.qml:99: TypeError: Type error
Nov 13 12:36:28 gseaborn plasmashell[2773]: file:///usr/lib64/qt5/qml/QtQuick/Controls/Button.qml:99: TypeError: Type error

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))

  1.start Nixnote2
  2. press the sync button on the tool bar

## Specifications
  - Nixnote2 Version: 2.1.5-b-6e1ef20
  - Platform:
Fedora 30
KDE Plasma Version 5.15.5
Qt Version: 5.12.5
Kernel Version: 5.3.8-200.fc30.x86_64

I primarily use Nixnote2 for my 2019 Monthly Calendar, which I use as a deployment calendar.  Beyond that I am using it to track projects and work tasks.

Thanks in advance,
Gregory

**Comment by gseaborn** [comment]
[messages.zip](https://github.com/robert7/nixnote2/files/3843638/messages.zip)

**Comment by robert7** [comment]
I suggest delete the offending note (or examine contents of "note-content.xml" ... then try again

![image](https://user-images.githubusercontent.com/1135218/76678830-7990d700-65db-11ea-8579-e04154756e7c.png)

in case it doesn't help, then delete all data & sync all from scratch - this should always help
see https://github.com/robert7/nixnote2/wiki/HowTo---What-to-do-if-the-app-crashes
