### ISSUE TITLE
Sync errors (UNRECOGNIZED_ERROR_CODE)

### ISSUE THREAD

**Issue by irthomasthomas** [robert7/nixnote2#142]
Hi,

Trying to use this for the first time and syncing stopped after about a hundred notes. I'm on Ubuntu 18.04. In the error log it has this:
ERROR 2019-12-04 19:57:11.519 ( communication/communicationmanager.cpp @ 178 ) EDAMSystemException 
ERROR 2019-12-04 19:57:11.521 ( communication/communicationmanager.cpp @ 1201 ) EDAMSystemException Error Code: 2080716464 

 INFO 2019-12-04 19:57:11.522 ( nixnote.cpp @ 1900 ) "EDAMSystemException: Unknown error:EDAMSystemException: UNRECOGNIZED_ERROR_CODE" 
 INFO 2019-12-04 19:57:53.282 ( nixnote.cpp @ 1900 ) "Notes will be reindexed." 
ERROR 2019-12-04 19:58:04.666 ( communication/communicationmanager.cpp @ 178 ) EDAMSystemException 
ERROR 2019-12-04 19:58:04.668 ( communication/communicationmanager.cpp @ 1201 ) EDAMSystemException Error Code: 604009392 

 INFO 2019-12-04 19:58:04.668 ( nixnote.cpp @ 1900 ) "EDAMSystemException: Unknown error:EDAMSystemException: UNRECOGNIZED_ERROR_CODE" 
ERROR 2019-12-04 19:59:09.715 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:09.716 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:09.716 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:09.716 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:09.973 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:09.974 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:10.001 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:10.004 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:10.028 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:10.055 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:10.059 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:10.073 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:10.134 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:10.888 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:10.888 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:11.769 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:11.769 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:11.769 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:11.770 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-12-04 19:59:14.402 ( communication/communicationmanager.cpp @ 178 ) EDAMSystemException 
ERROR 2019-12-04 19:59:14.404 ( communication/communicationmanager.cpp @ 1201 ) EDAMSystemException Error Code: 604099680 

 INFO 2019-12-04 19:59:14.404 ( nixnote.cpp @ 1900 ) "EDAMSystemException: Unknown error:EDAMSystemException: UNRECOGNIZED_ERROR_CODE"

**Comment by robert7** [comment]
see #137
...
It seems something got wrong in error code recognition in the last qevercloud update which was made in v2.1.5

so you may meanwhile try use older version (e.g. by using AppImage) e.g. 2.1.4 or 2.1.3, then you may get better error message, I will later try to work out

**Comment by irthomasthomas** [comment]
@robert7 
Thanks. I've tried 2.1.4 so far and this produces the following log. Is it worth me trying another version? 
Cheers,
Thomas
INFO  2019-12-05 14:24:48.822 src/main.cpp:287 NixNote 2.1.4-b4919d0, build at Aug  9 2019 at 14:46:12, with Qt 5.11.0 running on 5.11.0
INFO  2019-12-05 14:24:48.822 src/main.cpp:290 To get more detailed startup logging use --logLevel=1
ERROR 2019-12-05 14:32:19.386 src/communication/communicationmanager.cpp:525 Exception stacktrace:
ERROR 2019-12-05 14:32:19.406 src/communication/communicationerror.cpp:86 "EDAMSystemException[1912]: EDAMSystemException: UNRECOGNIZED_ERROR_CODE"
ERROR 2019-12-05 14:32:19.414 src/threads/syncrunner.cpp:271 Error retrieving chunk
ERROR 2019-12-05 14:32:19.673 src/communication/communicationmanager.cpp:525 Exception stacktrace:
ERROR 2019-12-05 14:32:19.676 src/communication/communicationerror.cpp:86 "EDAMSystemException[1785]: EDAMSystemException: UNRECOGNIZED_ERROR_CODE"
WARN  2019-12-05 14:33:37.579 src/html/noteformatter.cpp:194 Note is inactive.  Setting to read-only. Note guid="9d89085d-0519-4810-ab33-7569f28f9cfb"

**Comment by robert7** [comment]
hi
2.1.5 changed to Evernote API 1.29
2.1.4 changed to Evernote API 1.28

so I would recommend try 2.1.3 - the problem itself will not go away, but maybe you become more meaningful message. I guess someway the code recognition gone wrong in the last qevercloud and or evernote C++ API (I did not yet have time to investigate in more detail). Once you have meaningful message, the you can fix the cause and return to the newest version. You can easily try the older version using AppImage, you don't need to deinstall the current version (in case you installed e.g. from PPA).

**Comment by irthomasthomas** [comment]
@robert7 Ok thanks. It looks like rate limit? 
 
INFO  2019-12-05 18:42:37.256 src/main.cpp:287 NixNote 2.1.3-bbbf0a1, build at May 15 2019 at 12:23:37, with Qt 5.11.0 running on 5.11.0
INFO  2019-12-05 18:42:37.256 src/main.cpp:290 To get more detailed startup logging use --logLevel=1
ERROR 2019-12-05 18:46:24.256 src/communication/communicationmanager.cpp:513 Exception stacktrace:
ERROR 2019-12-05 18:46:24.260 src/communication/communicationerror.cpp:86 "RateLimitExceeded[19]: API rate limit exceeded. Enable 'Sync' > 'Restart sync on API limit' or try again in 14 minutes ## EDAMSystemException: RATE_LIMIT_REACHED rateLimitDuration= 839 sec. # rateLimitDuration=͇"
ERROR 2019-12-05 18:46:24.260 src/threads/syncrunner.cpp:266 Error retrieving chunk
ERROR 2019-12-05 18:46:24.550 src/communication/communicationmanager.cpp:513 Exception stacktrace:
ERROR 2019-12-05 18:46:24.552 src/communication/communicationerror.cpp:86 "RateLimitExceeded[19]: API rate limit exceeded. Enable 'Sync' > 'Restart sync on API limit' or try again in 18 minutes ## EDAMSystemException: RATE_LIMIT_REACHED rateLimitDuration= 1049 sec. # rateLimitDuration=Й"

**Comment by robert7** [comment]
yes. its rate limit, so just wait 1 hour (or less according to log message), then retry
in case you did many changes (e.g. in other evernote client) then sync may take few hours to complete
this is limit on evernote server side and nixnote can't do anything with it (just wait)

**Comment by irthomasthomas** [comment]
No problem. Many thanks

**Comment by robert7** [comment]
I could easily revert to the qevercloud version from 2.1.3, but the update done in 2.1.4 & 2.1.5 both have reason.

The new API seem to work OK, just the error code decoding seems to be wrong. There are error codes numbered from 1 to 28.. but now we get error code like 604099680 ... :see_no_evil: 

I'll look at it later..

**Comment by knbknb** [comment]
my Nixnote Version: 201910160846~2.1.5~ubuntu16.04.1 on  Ubuntu 16.04 with Unity

I had this error, and was stuck at `"Download 0% complete".` (not a Rate Limit Problem)

Perhaps this happens because there are "closed" notebooks. Synching seems to work better when all notebooks are declared "open" in the Nixnote Settings, and I also disabled the automatic (e.g. on startup) and experimental sync options. I also re-authenticated with Nixnote.

Now as I am writing this, the sync process is working much better than before.
( I am at download 5% complete of my ~7000 notes. ). 

Just saying. 
Perhaps this helps someone.
