### ISSUE TITLE
Display notes according to attribute not working

### ISSUE THREAD

**Issue by Blackmatrixx** [robert7/nixnote2#143]
Expected
Clicking on any attributes related to time (e.g. Attribute/Created/Since/Last week) should display all notes created within the last week.

Actual behaviour
No notes are displayed although they were created within the last week

Version
Version: 201910160846~2.1.5~ubuntu18.04.1

**Comment by robert7** [comment]
>Clicking on any attributes related to time (e.g. Attribute/Created/Since/Last week) should display all notes created within the last week.

From where got you, that should work like that? :D
It doesn't work like that..

**Comment by robert7** [comment]
Seems to be a duplicity of #149
