### ISSUE TITLE
Empty newlines in new notes

### ISSUE THREAD

**Issue by hamishmb** [robert7/nixnote2#144]
So firstly I want to say thanks for picking this up and maintaining it, and thanks to all the previous developers. It's been great to have an open-source EverNote client for Linux. Due to issues with the service itself, I'm now using Joplin, but I thought I should leave a thank you note, and try to contribute in some small way by at least filing this bug.

## Expected vs. actual behavior

New note has some newlines in it by default, would prefer not to have them.

## Steps to reproduce the problem

  1. Create a new note
  2. See the empty newlines.

## Specifications

  - Version 2.1.5

**Comment by robert7** [comment]
Actually I inserted the newlines on purpose... as there were some problems with dragging files to new notes... This helped, but not always. If you are not using Nixnote, I guess you don't mind, I don't mind either--- co I'm closing the ticket

**Comment by hamishmb** [comment]
Ah that makes sense. You definitely did fix a lot of the bugs from the older versions. Thanks for all the hard work, in the end I had to switch because of Evernote's billing system being stupid, but this is a great program.
