### ISSUE TITLE
Feature suggested: in-app-link from other app to open note in NixNote2

### ISSUE THREAD

**Issue by CppRulz** [robert7/nixnote2#145]
Hello! 

I like to know, if the following is possible in NixNote2 under Ubuntu
and if not, if there is a chance you might implement it?

Under Windows, when I have a Evernote Link `evernote:///view/...../`
for example in a word document or html file, when I click it in
Word or Firefox, then Evernote will pop up with the linked note.

Under Ubuntu I found in the NixNote2 help that it could open
a note with its id: `nixnote2 signalGui --openNote --id=1`
but there is yet no command to open the note by this link.

So my question is, could you add an option to the signalGui command
to open a node by an url? Like:

`nixnote2 signalGui --openNote --url=evernote:///view/...../`

To not be mistaken, the in-app-links of Evernote within NixNote2 work perfectly,
but it would be so cool to jump to the notes from another application.

And as I just found this topic: [Real Note Links](https://github.com/robert7/nixnote2/issues/84):
if I use this real note links, then the browser opens and asks me to log into Evernote.
I would like an "external" in-app-link to open in NixNote2, as I have the other app and
NixNote2 both open at the same computer.

Thanks a lot for maintaining NixNote and making Evernote available on Linux!

**Comment by robert7** [comment]
Hi,
it should be quite easy to implement..

For me personally... sorry currently I have almost no time for this project.. So I basically only doing maintenance & critical bugs, in case some happen to be found.

Additionally recently I switched to macOS... I can't even currently compile and use Nixnote directly on my machine :( (I will later try to find out how to compile it on macOS).

Pull requests welcomed :)

**Comment by rodelrod** [comment]
@robert7 How would you go about doing this? I want this feature too and would be willing to give it a shot but have very little available time so any lead is welcome.

**Comment by robert7** [comment]
So there is already a code, which can open a note by its ID (by starting 2nd instance of Nixnote which signals the other running instance, to open particular note).

The code to open the node itself in nixnote.cpp line 2761 (look for command "OPEN_NOTE").
If I'm understand it right, then expected ID is "LID" (or local ID), you need to adjust the search, that it extracts the GUID from the Evernote protocol link, then search by GUID.. 

Passing signal to running Nixnote is in cmdlinetool.cpp line 805. You need to extract the GUID from the "--url" parameter here and pass the GUID in the signal command.

That should be it :)

**Comment by rodelrod** [comment]
Thanks @robert7 
Please take a look at this PR: https://github.com/robert7/nixnote2/pull/150

**Comment by robert7** [comment]
Thanks, I'll look at it!

**Comment by robert7** [comment]
Added new command options for "signalGui" --openNoteUrl,  --openExternalNoteUrl,  --openNoteNewTabUrl   thanks to Rodrigo Eliseu, https://github.com/rodelrod

Available from version 2.1.6-rc3 (now merged to development branch)

**Comment by CppRulz** [comment]
Thank you Robert and Rodrigo!! You guys are the best! This is sooo great! :-)
