### ISSUE TITLE
Failure occurred in build

### ISSUE THREAD

**Issue by greenie537** [robert7/nixnote2#146]
Hi, newb here..I'm trying to get this built, but keep getting the error

 ~]$ git clone https://aur.archlinux.org/nixnote2-git.git
Cloning into 'nixnote2-git'...
remote: Enumerating objects: 97, done.
remote: Counting objects: 100% (97/97), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 97 (delta 16), reused 97 (delta 16)
Unpacking objects: 100% (97/97), 23.33 KiB | 1.94 MiB/s, done.
[greenie@archx ~]$ ls
Desktop  Downloads  nixnote2-git  xviewer-git
[greenie@archx ~]$ makepkg --syncdeps
==> ERROR: PKGBUILD does not exist.
[greenie@archx ~]$ ls
Desktop  Downloads  nixnote2-git  xviewer-git
[greenie@archx ~]$ cd nixnote2-git
[greenie@archx nixnote2-git]$ makepkg --syncdeps
==> Making package: nixnote2-git 2.1.1.r3.gf5e206dd-1 (Sun 02 Feb 2020 09:24:50 NZDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning nixnote2 git repo...
Cloning into bare repository '/home/greenie/nixnote2-git/nixnote2'...
remote: Enumerating objects: 84, done.
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 19708 (delta 51), reused 47 (delta 29), pack-reused 19624
Receiving objects: 100% (19708/19708), 68.40 MiB | 5.75 MiB/s, done.
Resolving deltas: 100% (14266/14266), done.
  -> Found tidy-source-dir-location.patch
==> Validating source files with sha256sums...
    nixnote2 ... Skipped
    tidy-source-dir-location.patch ... Passed
==> Extracting sources...
  -> Creating working copy of nixnote2 git repo...
Cloning into 'nixnote2'...
done.
==> Starting pkgver()...
==> Updated version: nixnote2-git 2.1.5.r1.g8ddf81fa-1
==> Starting build()...
/home/greenie/nixnote2-git/PKGBUILD: line 29: patch: command not found
==> ERROR: A failure occurred in build().
    Aborting...
[greenie@archx nixnote2-git]$ 
..this a issue TEMPLATE.. before posting pls delete the parts, which are not relevant..

Thanks heaps in advance

**Comment by robert7** [comment]
The error message is `patch: command not found`
.. meaning build system needs `patch` utility
but I dpn't use Arch linux... so I may not know how to help you
you may try to contact Ataraxy - https://aur.archlinux.org/packages/nixnote2-git/ 
@HaleTom

**Comment by HaleTom** [comment]
I thought that patch was a dependency for pkgbuild... Please confirm if you have /use/bin/patch and it's version.

**Comment by robert7** [comment]
Close, as there is no reply..
