### ISSUE TITLE
Sync error (EDAMUserException ENML_VALIDATION Attribute "aria-hidden" must be declared for element type "span")

### ISSUE THREAD

**Issue by jhaiduce** [robert7/nixnote2#152]
## Expected vs. actual behavior

Expect sync to complete successfully. Instead an error occurs, a "Sync Error" dialog appears, and the following message appears in the status bar: 

EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=Attribute \"aria-hidden\" must be declared for element type \"span\".

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))

  1. Press sync button

[messages.log](https://github.com/robert7/nixnote2/files/4606358/messages.log)

## Specifications

  - [Version](https://github.com/robert7/nixnote2/wiki/HowTo---Check-used-application-version): 2.1.6

**Comment by robert7** [comment]
You someway managed to add HTML "span" item in one of your notes with attribute "aria-hidden" .. which was not catched by automatic cleanup. Easiest if you fix text of your note.
You can e.g. convert all to text and paste (if its possible for the content).
Or you could edit HTML manually e.g. by "View/Source".
It should not be an usual case, so manual fix could be OK here.

**Comment by jhaiduce** [comment]
I had wondered if it was the content of a note that was the problem, but from the error message I couldn't tell what note was the culprit. Per your suggestion I exported all notes to a file (File->Export all notes) and searched for aria-hidden in the resulting file. One of my notes contained material pasted from a website that contained the aria-hidden attribute. 

For future, perhaps nixnote2 could provide some indication to the user what note is causing the problem in the event that an HTML tag causes a sync error.

In the meantime, however, I have manually deleted the offending <span> tags and my notes are syncing again. Thank you!

**Comment by robert7** [comment]
normally all offending markup is cleaned up automatically
i'll recheck the code for "<span>"

**Comment by povode** [comment]
is there a way to get an indication of which file might contain the offending html?
Log doesn't state any specific note :(

**Comment by robert7** [comment]
yes. you need to run nixnote with "DEBUG" level log, then you should see
But the note is also indicated as unsynced by the triangle before name
![image](https://user-images.githubusercontent.com/1135218/82988853-1a4b3c00-9ffa-11ea-9356-9c8d0a6fd1c7.png)
also you can turn on the "Sync" column, where you see, which notes are unsynced

![image](https://user-images.githubusercontent.com/1135218/82988952-3bac2800-9ffa-11ea-86e9-04e192ddcdfe.png)
