### ISSUE TITLE
Import all notes, tag issue

### ISSUE THREAD

**Issue by nicocappella** [robert7/nixnote2#153]
## Importing Notes from a backup, problem with the tags in each note
When importing a backup, it imports the notes, the notebooks and the tags, but each note doesn't have the tags thas is in the backup.nnex in fact they have none tag all the notes, i try modifying the backup file but didn't work.

## Specifications

  - Version: 2.1.6-1d56cf0 the AppImage version.

**Comment by boo-yee** [comment]
Hi, this issue has been fixed by pr #188. Hope the reply is not too late.
