### ISSUE TITLE
editor fonts and sorting notes

### ISSUE THREAD

**Issue by kunilovskaya** [robert7/nixnote2#156]
I am using NixNote since 2014. Thank you for developing the app.
Since the last upgrade -- my current NixNote verson is 202005061504_2.1.6_ubuntu18.04.1, I cannot 1) change the size of the fonts in the editor, which is set to annoyingly small 9; the font for the GUI does change from the settings
2) sort the search results by clicking on the Date Updated and Title Tabs in the Search results. I see that I can set the sort options in View > Sort notes by , but the previous sorting was more flexible.

**Comment by robert7** [comment]
hi,
ad1: you should be able to change both default font size and also set specific part of specific note to any font/size. See picture
ad2: sorting is as you described. If anyone wants to improve.. pull request is welcomed

![image](https://user-images.githubusercontent.com/1135218/83750432-95999700-a665-11ea-8ca0-acbae59316ce.png)

**Comment by boo-yee** [comment]
Hi, this issue has been fixed by pr #187 and pr #190.
