### ISSUE TITLE
tidy.h path differs on Archlinux

### ISSUE THREAD

**Issue by Novite5** [robert7/nixnote2#157]
After install `tidy` from archlinux's “extra”  repositorium, the header file `tidy.h` exists in `/usr/include`, same with macOS. 
`/usr/include/tidy.h`

This causes failure of qmake process.

`src/main.cpp:53:10: schwerwiegender Fehler: tidy/tidy.h: Datei oder Verzeichnis nicht gefunden
   53 | #include <tidy/tidy.h>
      |          ^~~~~~~~~~~~~
Kompilierung beendet.
`

Change `main.cpp` include header files part to the macOS lines, fixed this problem.

**Comment by robert7** [comment]
I guess there is a patch for it in https://aur.archlinux.org/cgit/aur.git/tree/tidy-source-dir-location.patch?h=nixnote2-git

see also https://aur.archlinux.org/packages/nixnote2-git/

unfortunately there are 2 variants, there tidy can be found... so you patch after download then compile

**Comment by Novite5** [comment]
Unfortunately, the patch doesn't work anymore. It returns the output:
```
patching file src/html/enmlformatter.cpp
Hunk #1 FAILED at 23.
1 out of 1 hunk FAILED -- saving rejects to file src/html/enmlformatter.cpp.rej
patching file src/main.cpp
Hunk #1 FAILED at 46.
1 out of 1 hunk FAILED -- saving rejects to file src/main.cpp.rej
```
Without CPP knowledge, I have no idea how to fix it.

**Comment by robert7** [comment]
..just manually change the 2 paths so the build finds the "tidy" includes... I think 4 lines need to be changed.. you do see it in the patch
![image](https://user-images.githubusercontent.com/1135218/84758979-6d475c00-afc6-11ea-8d40-eb657bb576c1.png)

**Comment by robert7** [comment]
.. in "enmlformatter.cpp" & "main.cpp" remove "tidy/"

**Comment by Novite5** [comment]
It works. Thank you very much.
