### ISSUE TITLE
Sync halts with "Host not found" error.

### ISSUE THREAD

**Issue by andy-lawson** [robert7/nixnote2#158]
## Expected vs. actual behavior
Periodically, Evernote sync pauses.
The following errors are present in the `messages.log` file;
`WARN  2020-06-16 01:35:23.500 src/qevercloud/QEverCloud/src/http.cpp:176 QEverCloud.http.simpleDownload: reply for url="https://www.evernote.com/edam/note/s323" is error: "Host  not found" => EverCloudException "Host  not found"
ERROR 2020-06-16 01:35:23.501 src/application.cpp:45 **********************************************************
ERROR 2020-06-16 01:35:23.502 src/application.cpp:46 **********************************************************
ERROR 2020-06-16 01:35:23.502 src/application.cpp:47 **********************************************************
ERROR 2020-06-16 01:35:23.502 src/application.cpp:48 **********************************************************
ERROR 2020-06-16 01:35:23.502 src/application.cpp:49 **********************************************************
ERROR 2020-06-16 01:35:23.502 src/application.cpp:50 **********************************************************
ERROR 2020-06-16 01:35:23.502 src/application.cpp:51 **********************************************************
ERROR 2020-06-16 01:35:23.502 src/application.cpp:52 std::exception was caught: Host  not found
`

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))

  1. Start the application.
  1. Perform a long sync operation like initial sync.
  1. Error occurs after a few hours.
  1. Restarting the app clears the error and sync resumes.

## Specifications
Ubuntu 18.04
nixnote2 2.1.6

**Comment by robert7** [comment]
this looks like you have network problems... so sometimes the "www.evernote.com" is not found.. => "Host not found"
