### ISSUE TITLE
New Changes Ready for Pull Request

### ISSUE THREAD

**Issue by MRC01** [robert7/nixnote2#16]
I frequently have multiple note windows open on multiple desktops. Syncing becomes a pain, because I have to find the main window to Sync. I'd like to be able to sync from any note window, not just the main window.
I updated the source code and added this feature, on a new branch called "f9Everywhere". Now the sync button is available on all note window toolbars. Click any of them and it syncs as if from the main screen.
This Git repo won't let me push this back to the repo. Could you please allow so I can submit the pull request?

**Comment by robert7** [comment]
Hi. 
>I updated the source code and added this feature, on a new branch called "f9Everywhere".

Ok. great!

You don't need push rights. It works like this:
1. fork mine repository. 
2. Then push the feature branch in your fork repo.
3. Then from there you can open the pull request. This is standard way how github works. Let me know, if it doesn't work..

E.g. I also have no push rights in the upstream repository and I were able to open pull request (which sadly no one is able to merge).

**Comment by MRC01** [comment]
Great. I just submitted the pull request.

**Comment by robert7** [comment]
thx; I'll look at it

**Comment by robert7** [comment]
PR merged. Thanks.

Note that if you want to compile now, there is slight change in the project (I described it in the main README). The Tidy library now needs to be compiled to a fixed path "/opt/tidy56" (you can either compile it there yourself or install "html-tidy56" from my new [PPA](https://launchpad.net/~robert7/+archive/ubuntu/nixnote21).
The app  can also now be installed from PPA, but its not yet 100% finished (but already pretty close).
