### ISSUE TITLE
Batch actions on notes: move / delete / tag

### ISSUE THREAD

**Issue by HaleTom** [robert7/nixnote2#160]
Is it possible to select multiple notes and move them as a batch to a new notebook?

I realised that my default notebook was incorrect for some time, and I have dozens of notes to move.

**Comment by HaleTom** [comment]
I can't work out how to do this on Evernote web, either :(

**Comment by HaleTom** [comment]
I doesn't seem possible to do this via the web:
https://discussion.evernote.com/forums/topic/90681-selectmark-multiple-notes-to-movedeletetag/

That link highlighted that move / delete / tag are also bulk options... updating title.

**Comment by msbentley** [comment]
This is possible in Nixnote - just select as many as you like and drag and drop them to the appropriate notebook in the notebook list. You will see in the note list that the notebook is updated.

**Comment by HaleTom** [comment]
Be very careful moving notes from a shared notebook because of #108.  Use Evernote web instead for now.
