### ISSUE TITLE
NixNote2 AppImage crashes without warning or error on Fedora 31

### ISSUE THREAD

**Issue by benblasco** [robert7/nixnote2#164]
## Expected vs. actual behavior
NixNote2 launches and then core dumps with the following error about 5 seconds after launch:

[user@host logs-2]$ /usr/local/bin/NixNote2-x86_64.AppImage --logLevel=1 >> /tmp/nixnote2.log 2>&1
Floating point exception (core dumped)

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))

  1. Install nixnote2 from appimage
  2. Launch
  3. Wait a few seconds

## Specifications
  - Version 2.1.6-1d56cf0 and also 2.1.6-aa5cfeb
[nixnote2.log](https://github.com/robert7/nixnote2/files/5344479/nixnote2.log)

Please let me know if there is more info I can provide or anything else I can add to help diagnosing the problem.

On a side note, are there plans to merge the work you have done with the work done at the location below?
https://github.com/jeffkowalski/Nixnote2

**Comment by robert7** [comment]
I know about one case where AppImage crashes wirh "Floating point exception" (like in your case) - see https://github.com/robert7/nixnote2/issues/55
I guess is a bug in Qt 5.5 used in default AppImage.

Workaround may be experimental AppImage build with Qt 5.11 - download at https://github.com/robert7/nixnote2/releases
File: NixNote2-qt511-x86_64.AppImage

also general info see: https://github.com/robert7/nixnote2/wiki/HowTo---What-to-do-if-the-app-crashes

>On a side note, are there plans to merge the work you have done with the work done at the location below?
>https://github.com/jeffkowalski/Nixnote2

I don't know nothing about the changes, but I gladly accept meaningful pull requests.

**Comment by eraser215** [comment]
The version with Qt 5.11 appears to be stable.  Thanks for sharing.  It would be nice to merge everybody's work on the platform together, so I will contact the other dev and see what he thinks so we all save duplication and take the software forward.
