### ISSUE TITLE
Synchronization error

### ISSUE THREAD

**Issue by Gnom7i** [robert7/nixnote2#165]
Hello!
I'm trying to sync 6300 notes from Evernote, but after syncing 5200 notes, an error occurred. Please tell me how to fix it?

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))
INFO  2020-10-16 21:52:34.470 src/main.cpp:304 NixNote 202005061502~2.1.6~ubuntu20.04.1, build at May  6 2020 at 15:02:08, with Qt 5.12.8 running on 5.12.8
INFO  2020-10-16 21:52:34.470 src/main.cpp:307 To get more detailed startup logging use --logLevel=1
WARN  2020-10-16 21:53:04.533 src/nixnote.cpp:228 encrypt.encrypt failed
INFO  2020-10-16 21:53:05.183 src/nixnote.cpp:2629 SHOW_WINDOW requested by shared memory segment.
ERROR 2020-10-16 21:53:10.208 src/communication/communicationmanager.cpp:537 Exception stacktrace:
ERROR 2020-10-16 21:53:10.211 src/communication/communicationerror.cpp:88 "EDAMSystemException[code=813221504]: EDAMSystemException: UNRECOGNIZED_ERROR_CODE"
ERROR 2020-10-16 21:59:19.258 src/communication/communicationmanager.cpp:537 Exception stacktrace:
ERROR 2020-10-16 21:59:19.263 src/communication/communicationerror.cpp:88 "EDAMSystemException[code=813221504]: EDAMSystemException: UNRECOGNIZED_ERROR_CODE"

## Specifications

  - [Version](https://github.com/robert7/nixnote2/wiki/HowTo---Check-used-application-version): 202005061502~2.1.6~ubuntu20.04.1

**Comment by robert7** [comment]
check https://github.com/robert7/nixnote2/issues/163 and https://github.com/robert7/nixnote2/issues/155
