### ISSUE TITLE
In-App Note links don't work when there is an apostrophe in the title

### ISSUE THREAD

**Issue by lubobde** [robert7/nixnote2#168]
Nixnote2 Ver. 202005061504  2.1.6 on ubuntu18.04.1

## What happens
It is not possible to create In App Note Links if there is an apostrophe in the title.

"Not possible" means: If you create an In App Note link, either by using the mouse right click or the Ctr-Shift-K shortcut and then use "paste", either in the same document or in an other document, nothing will be inserted.

## How to reproduce

1. Create a note with this title:
"This is Lucius' test text"

2. Select "Copy In-App Note Link" with right click

3. Click into document and choose "paste" from right click menu

## What else
I have also tested this with ", #, `, `, ^ and ° . With those no problem occurred.

--- 
And thanks for the good work !
Best, Lucius

**Comment by boo-yee** [comment]
Fixed by pr#192.
