### ISSUE TITLE
Gentoo: add to main Portage tree instead of the overlay

### ISSUE THREAD

**Issue by vitaly-zdanevich** [robert7/nixnote2#173]
It will be easier for users to find and install.

**Comment by robert7** [comment]
see #170
unfortunately I have no time for the project... you are free to contribute and make a fork of pull request here

**Comment by vitaly-zdanevich** [comment]
Ok, I will try to add Nixnote to the Gentoo main repo.

**Comment by vitaly-zdanevich** [comment]
Still not in the main tree, but in Guru https://github.com/gentoo/guru/tree/master/app-office/nixnote-bin

**Comment by robert7** [comment]
OK. To be honest, I don't know anything about deployment/packaging in Gentoo. 

In any case, pull requests are welcome. 

Just forgive me, if I don't want to change cosmetic things, which I used for last X years, as the project is in kind of maintenance mode.

Feel free to reopen any issues, which I closed prematurely. I closed yesterday all tickets, which I felt are someway stale.
