### ISSUE TITLE
Does not start up completely, Resource not found for lid:

### ISSUE THREAD

**Issue by mckellygit** [robert7/nixnote2#177]
Hi,

Thank you for nixnote2
After an apt-get update/upgrade of my Ubuntu 18.04 system today, nixnote2 does not start up anymore.
When starting I see -

WARN  2021-09-22 07:47:39.148 src/utilities/crossmemorymapper.cpp:57 Shared memory segment failed to allocate, instance key="047a0180-2482-4fc2-b765-0ba7f31856861"; error=4, "QSharedMemory::create: already exists"
INFO  2021-09-22 07:47:39.148 src/main.cpp:225 New shared memory segment could not be created; code=4
INFO  2021-09-22 07:47:39.148 src/utilities/crossmemorymapper.cpp:62 Shared memory segment allocated, instance key: "047a0180-2482-4fc2-b765-0ba7f31856861"
INFO  2021-09-22 07:47:39.148 src/main.cpp:304 NixNote 202109081010~2.1.6~ubuntu18.04.1, build at Sep  8 2021 at 10:10:36, with Qt 5.9.5 running on 5.9.5
INFO  2021-09-22 07:47:39.148 src/main.cpp:307 To get more detailed startup logging use --logLevel=1
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
ERROR 2021-09-22 07:47:39.879 src/sql/resourcetable.cpp:774 Resource not found for lid:14257 key:6003 hash:"8c286f87edaba8e630c608e6a4e008f8"
ERROR 2021-09-22 07:47:39.898 src/sql/resourcetable.cpp:774 Resource not found for lid:14258 key:6003 hash:"8c286f87edaba8e630c608e6a4e008f8"
\<repeats thousands of msgs like this ...\>

And this goes on for a long time and never seems to finish or resolve itself.
Any idea ?  Its been fine for years until now :-)
The upgrade probably changed some lib used, but any idea where to look next for possibly reverting a lib or something ?

thx,
-m

**Comment by mckellygit** [comment]
These are some libs / pkgs on my system -
libQt5Sql.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5
libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
libqt5sql5:amd64                           5.9.5+dfsg-0ubuntu2.6                                            amd64        Qt 5 SQL module
libqt5sql5-sqlite:amd64                    5.9.5+dfsg-0ubuntu2.6                                            amd64        Qt 5 SQLite 3 database driver
libsqlite3-0:amd64                         3.22.0-1ubuntu0.4                                                amd64        SQLite 3 shared library

**Comment by robert7** [comment]
> Resource not found for lid:14258

it looks like your local database is corrupted for some reason (nixnote2 uses sqlite)

in case you synced to cloud recently, you could try sync in new directory (using configDir parameter)

see steps in https://github.com/robert7/nixnote2/wiki/HowTo---What-to-do-if-the-app-crashes
