### ISSUE TITLE
Feature request:  for "Unknown Tag record key: 1004" errors, print the tag

### ISSUE THREAD

**Issue by MisterScott** [robert7/nixnote2#178]
Sync is failing.  Popup:  "Sync error. See message log for details", with status line:
"Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Element type "header" must be declared."
I understand that one possible cause is a tags mismatch between NixNote2 and Evernote.  I have over 100 tags, have added some both in Evernote and NixNote2, as well as (IIRC) editing some tags.  
The message log includes many:
`ERROR 2021-10-01 09:56:48.071 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 `

Requested feature:  please indicate _which_ tag is unknown, not present, or is a mismatch, or whatever other hints for debugging are available.  Indicating _which_ note(s) have issues might also be helpful.

## Expected vs. actual behavior
Expected:  message log gives some hint as to _which_ tag is unknown.
Actual:  many instances of the same message:
`ERROR 2021-10-01 09:56:48.071 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 `

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))
Don't know how I made it happen.
I have over 100 tags, have added some both in Evernote and NixNote2, as well as (IIRC) editing some tags.  I have notes with conflicts.
Messages.log attached.
[messages.log](https://github.com/robert7/nixnote2/files/7280082/messages.log)

## Specifications
NixNote 2.0.2

**Comment by boo-yee** [comment]
It seems that it has been fixed. https://github.com/baumgarr/nixnote2/pull/443
