### ISSUE TITLE
Can't search / replace with <space> as replacement text

### ISSUE THREAD

**Issue by HaleTom** [robert7/nixnote2#180]
## Expected vs. actual behavior
Expected: I can replace found text with one or more ' ' (space).

Actual: The found text is removed

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))

  1. Create a new note
  1. Type `foobar`
  1. Ctrl-H
  1. Search: 'oo'
  2. Replace: <space> (or <space><space>)
  3. Click Replace
  4. Observe that the text is just `fbar` with no space(s)

## Specifications

  - Version: 2.1.6-460aec81

## Context

I am trying to work around #172 (Random characters appear in sync) by replacing `Â ` with ` `.

**Comment by boo-yee** [comment]
Hi, this issue has been fixed by pr #186.

**Comment by HaleTom** [comment]
Awesomeness, thanks a bunch!!
