### ISSUE TITLE
copy and paste from Visual Studio Code removes spaces and tabulators

### ISSUE THREAD

**Issue by wolfpirker** [robert7/nixnote2#191]
Hello,

I noticed after copying code from Visual Studio Code into a note of nixnote it first looks alright with whitespaces and formatting, but after I restart nixnote, then the whitespaces at the beginning of lines are gone. If the insert happens in a list, after are restart of Nixnote there are often additional empty newlines. 

I am using Nixnote 2.1.2-1 on a Linux. It only happens when using the normal insert with formatting (Ctrl+V), insert without formatting (Ctrl+Shift+V) is not affected.

**Comment by boo-yee** [comment]
Could you post the note source(via 'view'-'show source' in Nixnote) right after you paste the code from VS Code?

**Comment by wolfpirker** [comment]
ya sure, so right after pasting the code from VS Code:
`my VS Code version:<div><div>Version: 1.69.0</div><div>Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9</div><div>Date: 2022-07-07T08:29:47.439Z</div><div>Electron: 18.3.5</div><div>Chromium: 100.0.4896.160</div><div>Node.js: 16.13.2</div><div>V8: 10.0.139.17-electron.0</div><div>OS: Linux x64 4.19.0-21-amd64</div></div><div><br></div><div>Nixnote:&nbsp;<b style="text-align: center;">Version: 2.1.2-1</b></div><div><b style="text-align: center;"><br></b></div><div><b style="text-align: center;"><br></b></div><div><div style="color: rgb(212, 212, 212); background-color: rgb(30, 30, 30); font-family: 'Droid Sans Mono', monospace, monospace; font-size: 14px; line-height: 19px; white-space: pre;"><div><span style="color: #569cd6;">namespace</span> <span style="color: #4ec9b0;">HotelListingAPI</span>.<span style="color: #4ec9b0;">VSCode</span>.<span style="color: #4ec9b0;">Repository</span></div><div>{</div><div>    <span style="color: #569cd6;">public</span> <span style="color: #569cd6;">class</span> <span style="color: #4ec9b0;">GenericRepository</span>&lt;<span style="color: #4ec9b0;">T</span>&gt; : <span style="color: #4ec9b0;">IGenericRepository</span>&lt;<span style="color: #4ec9b0;">T</span>&gt; <span style="color: #569cd6;">where</span> <span style="color: #4ec9b0;">T</span> : <span style="color: #569cd6;">class</span></div><div>    {</div><div>        <span style="color: #569cd6;">private</span> <span style="color: #569cd6;">readonly</span> <span style="color: #4ec9b0;">HotelListingDbContext</span> <span style="color: #9cdcfe;">_context</span>;</div><div>        <span style="color: #569cd6;">private</span> <span style="color: #569cd6;">readonly</span> <span style="color: #4ec9b0;">IMapper</span> <span style="color: #9cdcfe;">_mapper</span>;</div><br><div>        <span style="color: #569cd6;">public</span> <span style="color: #4ec9b0;">GenericRepository</span>(<span style="color: #4ec9b0;">HotelListingDbContext</span> <span style="color: #9cdcfe;">context</span>,  <span style="color: #4ec9b0;">IMapper</span> <span style="color: #9cdcfe;">mapper</span>)</div><div>        {</div><div>            <span style="color: #569cd6;">this</span>.<span style="color: #9cdcfe;">_context</span> = <span style="color: #9cdcfe;">context</span>;</div><div>            <span style="color: #569cd6;">this</span>.<span style="color: #9cdcfe;">_mapper</span> = <span style="color: #9cdcfe;">mapper</span>;</div><div>        }</div><br><div>        <span style="color: #569cd6;">public</span> <span style="color: #569cd6;">async</span> <span style="color: #4ec9b0;">Task</span>&lt;<span style="color: #4ec9b0;">T</span>&gt; <span style="color: #dcdcaa;">AddAsync</span>(<span style="color: #4ec9b0;">T</span> <span style="color: #9cdcfe;">entity</span>)</div><div>        {</div><div>            <span style="color: #569cd6;">await</span> <span style="color: #9cdcfe;">_context</span>.<span style="color: #dcdcaa;">AddAsync</span>(<span style="color: #9cdcfe;">entity</span>);</div><div>            <span style="color: #569cd6;">await</span> <span style="color: #9cdcfe;">_context</span>.<span style="color: #dcdcaa;">SaveChangesAsync</span>();</div><div>            <span style="color: #c586c0;">return</span> <span style="color: #9cdcfe;">entity</span>;</div><div>        }</div></div></div>`

**and after closing and starting Nixnote again**, it is like this:
`my VS Code version:
<div>
<div>Version: 1.69.0</div>
<div>Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9</div>
<div>Date: 2022-07-07T08:29:47.439Z</div>
<div>Electron: 18.3.5</div>
<div>Chromium: 100.0.4896.160</div>
<div>Node.js: 16.13.2</div>
<div>V8: 10.0.139.17-electron.0</div>
<div>OS: Linux x64 4.19.0-21-amd64</div>
</div>
<div><br></div>
<div>Nixnote:&nbsp;<b style="text-align: center;">Version:
2.1.2-1</b></div>
<div><br></div><div><br></div>
<div>
<div style="color: rgb(212, 212, 212); background-color: rgb(30, 30, 30); font-family: 'Droid Sans Mono', monospace, monospace; font-size: 14px; line-height: 19px; white-space: pre;">
<div><span style="color: #569cd6;">namespace</span> <span style="color: #4ec9b0;">HotelListingAPI</span>.<span style="color: #4ec9b0;">VSCode</span>.<span style="color: #4ec9b0;">Repository</span></div>
<div>{</div>
<div><span style="color: #569cd6;">public</span> <span style="color: #569cd6;">class</span> <span style="color: #4ec9b0;">GenericRepository</span>&lt;<span style="color: #4ec9b0;">T</span>&gt; : <span style="color: #4ec9b0;">IGenericRepository</span>&lt;<span style="color: #4ec9b0;">T</span>&gt; <span style="color: #569cd6;">where</span> <span style="color: #4ec9b0;">T</span> : <span style="color: #569cd6;">class</span></div>
<div>{</div>
<div><span style="color: #569cd6;">private</span> <span style="color: #569cd6;">readonly</span> <span style="color: #4ec9b0;">HotelListingDbContext</span> <span style="color: #9cdcfe;">_context</span>;</div>
<div><span style="color: #569cd6;">private</span> <span style="color: #569cd6;">readonly</span> <span style="color: #4ec9b0;">IMapper</span> <span style="color: #9cdcfe;">_mapper</span>;</div>
<br>
<div><span style="color: #569cd6;">public</span> <span style="color: #4ec9b0;">GenericRepository</span>(<span style="color: #4ec9b0;">HotelListingDbContext</span> <span style="color: #9cdcfe;">context</span>, <span style="color: #4ec9b0;">IMapper</span> <span style="color: #9cdcfe;">mapper</span>)</div>
<div>{</div>
<div><span style="color: #569cd6;">this</span>.<span style="color: #9cdcfe;">_context</span> = <span style="color: #9cdcfe;">context</span>;</div>
<div><span style="color: #569cd6;">this</span>.<span style="color: #9cdcfe;">_mapper</span> = <span style="color: #9cdcfe;">mapper</span>;</div>
<div>}</div>
<br>
<div><span style="color: #569cd6;">public</span> <span style="color: #569cd6;">async</span> <span style="color: #4ec9b0;">Task</span>&lt;<span style="color: #4ec9b0;">T</span>&gt; <span style="color: #dcdcaa;">AddAsync</span>(<span style="color: #4ec9b0;">T</span> <span style="color: #9cdcfe;">entity</span>)</div>
<div>{</div>
<div><span style="color: #569cd6;">await</span> <span style="color: #9cdcfe;">_context</span>.<span style="color: #dcdcaa;">AddAsync</span>(<span style="color: #9cdcfe;">entity</span>);</div>
<div><span style="color: #569cd6;">await</span> <span style="color: #9cdcfe;">_context</span>.<span style="color: #dcdcaa;">SaveChangesAsync</span>();</div>
<div><span style="color: #c586c0;">return</span> <span style="color: #9cdcfe;">entity</span>;</div>
<div>}</div>
</div>
</div>
`
and here would be screenshots of it, before and after:
[https://ibb.co/Lx5Z5zt](url)
[https://ibb.co/yssYgGf](url)

**Comment by wolfpirker** [comment]
and after closing and starting Nixnote again, it is like this:
`my VS Code version:
<div>
<div>Version: 1.69.0</div>
<div>Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9</div>
<div>Date: 2022-07-07T08:29:47.439Z</div>
<div>Electron: 18.3.5</div>
<div>Chromium: 100.0.4896.160</div>
<div>Node.js: 16.13.2</div>
<div>V8: 10.0.139.17-electron.0</div>
<div>OS: Linux x64 4.19.0-21-amd64</div>
</div>
<div><br></div>
<div>Nixnote:&nbsp;<b style="text-align: center;">Version:
2.1.2-1</b></div>
<div><br></div>
<div><br></div>
<div>
<div style="color: rgb(212, 212, 212); background-color: rgb(30, 30, 30); font-family: 'Droid Sans Mono', monospace, monospace; font-size: 14px; line-height: 19px; white-space: pre;">
<div><span style="color: #569cd6;">namespace</span> <span style="color: #4ec9b0;">HotelListingAPI</span>.<span style="color: #4ec9b0;">VSCode</span>.<span style="color: #4ec9b0;">Repository</span></div>
<div>{</div>
<div><span style="color: #569cd6;">public</span> <span style="color: #569cd6;">class</span> <span style="color: #4ec9b0;">GenericRepository</span>&lt;<span style="color: #4ec9b0;">T</span>&gt; : <span style="color: #4ec9b0;">IGenericRepository</span>&lt;<span style="color: #4ec9b0;">T</span>&gt; <span style="color: #569cd6;">where</span> <span style="color: #4ec9b0;">T</span> : <span style="color: #569cd6;">class</span></div>
<div>{</div>
<div><span style="color: #569cd6;">private</span> <span style="color: #569cd6;">readonly</span> <span style="color: #4ec9b0;">HotelListingDbContext</span> <span style="color: #9cdcfe;">_context</span>;</div>
<div><span style="color: #569cd6;">private</span> <span style="color: #569cd6;">readonly</span> <span style="color: #4ec9b0;">IMapper</span> <span style="color: #9cdcfe;">_mapper</span>;</div>
<br>
<div><span style="color: #569cd6;">public</span> <span style="color: #4ec9b0;">GenericRepository</span>(<span style="color: #4ec9b0;">HotelListingDbContext</span> <span style="color: #9cdcfe;">context</span>, <span style="color: #4ec9b0;">IMapper</span> <span style="color: #9cdcfe;">mapper</span>)</div>
<div>{</div>
<div><span style="color: #569cd6;">this</span>.<span style="color: #9cdcfe;">_context</span> = <span style="color: #9cdcfe;">context</span>;</div>
<div><span style="color: #569cd6;">this</span>.<span style="color: #9cdcfe;">_mapper</span> = <span style="color: #9cdcfe;">mapper</span>;</div>
<div>}</div>
<br>
<div><span style="color: #569cd6;">public</span> <span style="color: #569cd6;">async</span> <span style="color: #4ec9b0;">Task</span>&lt;<span style="color: #4ec9b0;">T</span>&gt; <span style="color: #dcdcaa;">AddAsync</span>(<span style="color: #4ec9b0;">T</span> <span style="color: #9cdcfe;">entity</span>)</div>
<div>{</div>
<div><span style="color: #569cd6;">await</span> <span style="color: #9cdcfe;">_context</span>.<span style="color: #dcdcaa;">AddAsync</span>(<span style="color: #9cdcfe;">entity</span>);</div>
<div><span style="color: #569cd6;">await</span> <span style="color: #9cdcfe;">_context</span>.<span style="color: #dcdcaa;">SaveChangesAsync</span>();</div>
<div><span style="color: #c586c0;">return</span> <span style="color: #9cdcfe;">entity</span>;</div>
<div>}</div>
<br>
<div><span style="color: #569cd6;">public</span> <span style="color: #569cd6;">async</span> <span style="color: #4ec9b0;">Task</span> <span style="color: #dcdcaa;">DeleteAsync</span>(<span style="color: #569cd6;">int</span> <span style="color: #9cdcfe;">id</span>)</div>
<div>{</div>
<div><span style="color: #569cd6;">var</span> <span style="color: #9cdcfe;">entity</span> = <span style="color: #569cd6;">await</span> <span style="color: #dcdcaa;">GetAsync</span>(<span style="color: #9cdcfe;">id</span>);</div>
<div><span style="color: #9cdcfe;">_context</span>.<span style="color: #dcdcaa;">Set</span>&lt;<span style="color: #4ec9b0;">T</span>&gt;().<span style="color: #dcdcaa;">Remove</span>(<span style="color: #9cdcfe;">entity</span>);</div>
<div><span style="color: #569cd6;">await</span> <span style="color: #9cdcfe;">_context</span>.<span style="color: #dcdcaa;">SaveChangesAsync</span>();</div>
<div>}</div>
<br>
<div><span style="color: #569cd6;">public</span> <span style="color: #569cd6;">async</span> <span style="color: #4ec9b0;">Task</span>&lt;<span style="color: #569cd6;">bool</span>&gt; <span style="color: #dcdcaa;">Exists</span>(<span style="color: #569cd6;">int</span> <span style="color: #9cdcfe;">id</span>)</div>
<div>{</div>
<div><span style="color: #569cd6;">var</span> <span style="color: #9cdcfe;">entity</span> = <span style="color: #569cd6;">await</span> <span style="color: #dcdcaa;">GetAsync</span>(<span style="color: #9cdcfe;">id</span>);</div>
<div><span style="color: #c586c0;">return</span> <span style="color: #9cdcfe;">entity</span> != <span style="color: #569cd6;">null</span>;</div>
<div>}</div>
<br>
<div><span style="color: #569cd6;">public</span> <span style="color: #569cd6;">async</span> <span style="color: #4ec9b0;">Task</span>&lt;<span style="color: #4ec9b0;">List</span>&lt;<span style="color: #4ec9b0;">T</span>&gt;&gt; <span style="color: #dcdcaa;">GetAllAsync</span>()</div>
<div>{</div>
<div><span style="color: #c586c0;">return</span> <span style="color: #569cd6;">await</span> <span style="color: #9cdcfe;">_context</span>.<span style="color: #dcdcaa;">Set</span>&lt;<span style="color: #4ec9b0;">T</span>&gt;().<span style="color: #dcdcaa;">ToListAsync</span>();</div>
<div>}</div>
</div>
</div>
`

and here would be screenshots of it, before and after:
![after_pasting_2022-08-08_11-42-45](https://user-images.githubusercontent.com/3986957/183392266-c768f768-1f0e-4564-a68a-58b883f610fd.png)
![after_restart_2022-08-08_11-42-03](https://user-images.githubusercontent.com/3986957/183392289-df56636c-bffe-43e4-bdfc-c1baf4c5e157.png)

**Comment by boo-yee** [comment]
This is because vscode and nixnote have different treatments on the html. Vscode seems to not tidy the html, but nixnote always do that. I paste a JS script here to adapt nixnote to show the code copied from vscode correctly.

`var NOTEBOOK_NAME = "vscode";
var VSCODE_EDITOR_WHITE_SPACE_ATTR = "white-space: pre;";
var INDENT_SPACES_REG_EXP = /\s{4}/g;

var nb = note.getNotebook();
if (nb === NOTEBOOK_NAME) {
    var c = note.getContents();
    c = c.replace(VSCODE_EDITOR_WHITE_SPACE_ATTR, "");
    c = c.replace(INDENT_SPACES_REG_EXP, "&nbsp;&nbsp;&nbsp;&nbsp;");
    
    note.setContents(c);
}

`

**Comment by wolfpirker** [comment]
hey,
Thank you, for this solution or workaround. 
I just followed your instructions and tested it in a notebook with a name as specified as in the script. 

It works well so far. Really nice, that this bug is no issue anymore for me. Thanks!

**Comment by boo-yee** [comment]
Glad to help you.
