### ISSUE TITLE
ubuntu22.04 SSL Errors

### ISSUE THREAD

**Issue by luyanfeng** [robert7/nixnote2#194]
Login failed.
SSL Errors:
The peer did not present any certificate
The root certificate of the certificate chain is self-signed, and untrusted

![图片](https://user-images.githubusercontent.com/5779510/210710266-35fea870-5f32-4e19-a6d8-89b7b618e318.png)

**Comment by boo-yee** [comment]
There may be interceptions in your network. You may want to set your DNS server to 1.1.1.1 or 8.8.8.8, and try to login again.

**Comment by robert7** [comment]
Nixnote doesn't have any infrastructure (no servers) and doesn't contain any own SSL certificates. It only connects directly to the Evernote servers. 

As boo-yee said, something in your network setup seems to intercept the traffic and presents self-signed certificate.
