### ISSUE TITLE
2.1.8: please update this link https://github.com/robert7/nixnote2/releases/download/continuous-develop/NixNote2-x86_64.AppImage

### ISSUE THREAD

**Issue by vitaly-zdanevich** [robert7/nixnote2#200]
I hope that here we can always have the current version?

Currently this link have 2.1.7

I use this link for [Gentoo ebuild](https://github.com/gentoo/guru/blob/master/app-office/nixnote-bin/nixnote-bin-9999.ebuild).

**Comment by robert7** [comment]
normally the "continuous" build are build by Travis CI automatically...but for some reason this doesn't work now

i'll check that later

**Comment by robert7** [comment]
so I wrote an email to Travis CI support, I hope they give me some open source build credits 😀

**Comment by robert7** [comment]
the Travis builds are now fixed, and the assets are now updated, they should also update in the future

@d1vanov thanks for info, but if not needed, I don't want to migrate if not necessary (as this would require additional time)
