### ISSUE TITLE
AppImage file name must contain version number

### ISSUE THREAD

**Issue by vitaly-zdanevich** [robert7/nixnote2#201]
As a common practice, for usability.

And Gentoo cache based on the file name.

**Comment by robert7** [comment]
how do you mean that? where do you expect the version number?

**Comment by vitaly-zdanevich** [comment]
Here https://github.com/robert7/nixnote2/releases/download/v2.1.8/NixNote2-x86_64.AppImage

Like NixNote2.8.2-x86_64.AppImage

**Comment by robert7** [comment]
I did some googling, whenever there is some universal/best practice convention of naming release artefacts/assets, but actually did not find much.

So I guess it is a bit a matter of taste.

As all the previous releases use AppImage name with constant filename like `NixNote2-x86_64.AppImage` I leave it as it is for now.
The version is actually in the URL: `https://github.com/robert7/nixnote2/releases/download/v2.1.8/NixNote2-x86_64.AppImage`.

Further the version is **inside** of the AppImage, you can see it in the About box (after starting the file).
You can also unpack the AppLimage (`./NixNote2-x86_64.AppImage --appimage-extract`) and then find version in a text file  in `squashfs-root/usr/share/nixnote2/build-version.txt`.

As the project is rather in "maintenance mode", than in really actiove development, I prefer not to change cosmetic things.


![image](https://user-images.githubusercontent.com/1135218/232556718-c772a372-7dea-4a76-8d5d-4742c6355de8.png)

**Comment by vitaly-zdanevich** [comment]
About AppImage unpacking: is it a good for package managers? As I understand, after unpacking it will start faster?

**Comment by robert7** [comment]
>  As I understand, after unpacking it will start faster?

The difference may be negligible, but I'm not an expert in this area. As far I know, the "packed" AppImage is mounted via FUSE file system. And normally it is quite fast.
