### ISSUE TITLE
regression introduced in sorting code (pull #187) - narrow note list no longer sorted

### ISSUE THREAD

**Issue by ludovicaelbrecht** [robert7/nixnote2#204]
## Expected vs. actual behavior
I use the "narrow note list" and sort notes through _View -> Sort notes by -> Date Updated_. This has worked perfectly until 2.1.6, and has been broken in every version since 2.1.7.

## Steps to reproduce the problem
  1.  _View -> Narrow Note List_
  2. Try to sort the notes using _View -> Sort notes by -> Date Updated_
  3. The notes aren't sorted differently, they're always sorted alphabetically.

## Specifications

Running nixnote2 on Linux (Fedora 38), reproduced this behavior both using the Fedora copr package and by building from source.

 I looked at the changes introduced in 2.1.7 (since this is where the problem appears). In 2.1.7, this issue is closed: https://github.com/robert7/nixnote2/issues/156 ("_editor fonts and sorting notes_").
 Which is fixed by this pull request: https://github.com/robert7/nixnote2/pull/187/commits
 Which contains this commit: https://github.com/robert7/nixnote2/pull/187/commits/4fb6706146cfce61309c062e544df55e6f1faa7d
 
 If I undo this commit (i.e. comment out the sorting code and add "this->setSortingEnabled(false);" again), then recompile, the regression is no longer there for me.
 
 I don't know what the correct fix is, but if I read issue #156 correctly it seems that this commit fixed a sorting issue in "wide note list" mode, but as a side effect breaks sorting in "narrow note list".

Thanks,
Ludovic

**Comment by boo-yee** [comment]
Hi.
To fix issue 156, I set the notetableview as sortable by calling setSortingEnabled(true), so that we can sort by clicking on the headers, but I didn't know it has such a side effect. If you just need to sort by one attribute(column), you could do that by clicking on the notetableview's header for now. And I'll try to find a way to make the sort from the menu work later on.

**Comment by boo-yee** [comment]
Fixed by https://github.com/robert7/nixnote2/pull/207.

**Comment by ludovicaelbrecht** [comment]
Just built the develop branch, it's fixed indeed. Thanks a lot!
