### ISSUE TITLE
Clarity on build pipeline, branches, tags

### ISSUE THREAD

**Issue by HaleTom** [robert7/nixnote2#205]
Context: I'm thinking of splitting the Arch packages into `develop` and `release` and `appimage` (the last requiring no compilation, but larger)

I noticed tag: `continuous-develop` is not being updated. Last update was:

`eb6528d9 Merge remote-tracking branch 'origin/feature/rs-201910' into develop  (tag: continuous-develop)[3 years, 8 months ago Robert Spiegel]`

[This wiki page](https://github.com/robert7/nixnote2/wiki/Releases---versions%2C-build-pipeline%2C-branches%2C-tags) says:

> Tip of the `develop` branch is marked by tag `continuous-develop`

1. Is the `continuous-develop` tag needed anymore?
2. Has it been entirely replaced by `appimage`?
3. Does the `develop` branch always pass all integration checks / automated tests?
4. Is there any case where the tag `appimage` isn't applied to the tip of `develop`?  Only when Travis CI is in progress?

**Comment by robert7** [comment]
Hi Tom,
all what is described in the wiki page, should still be valid.
ad1: yes it is build out of develop
ad2: this question doesn't give me much sense. the app image is created from master (continuous) and from develop (continuous-develop) and for each tag - this the tag continuous-develop should work as described
ad3: yes, but to be honest there aren't many unit tests
ad4 there is not tag "appimage"; continuous & continuous-develop tags are created by travis CI builds running automatically after merge in develop or master

but you are right - for some reason the artefact for both continuous & continuous-develop haven't been updated for some reason - I now deleted both releases continuous & continuous-develop and restarted both Travis CI builds which hopefully will generate them new

**Comment by robert7** [comment]
all is now freshly generated and tags are set correctly
![image](https://github.com/robert7/nixnote2/assets/1135218/ab874198-9b1a-406d-9a12-c16494afc3df)

**Comment by HaleTom** [comment]
That all looks fantastic - thanks very much ☺️
