### ISSUE TITLE
develop branch - ccache added build dependency for the build-with-qmake.sh script not explicitely documented

### ISSUE THREAD

**Issue by prahal** [robert7/nixnote2#211]
Commit 03837e6b619 "Issue #171: switch docker build to Ubuntu focal and using system browser for OAuth" introduced a new build dependency on ccache for the `./development/build-with-qmake.sh` script.

Develop branch.

Was the added `QMAKE_CXX="ccache g++"` done on purpose or was a local build optimization that slept through?

Could it be related to the docker build process per the description?

The ccache added dependency might not be a leftover per it was added to the docker build dependencies.
Still, the README in the develop branch still point to the old docker file since then removed to tell the dependencies, that is https://github.com/robert7/nixnote2/blob/develop/development/docker/Dockerfile.ubuntu_xenial instead of the new https://github.com/robert7/nixnote2/blob/develop/development/docker/Dockerfile.ubuntu_focal (which has the ccache build dependency listed).

**Comment by d1vanov** [comment]
I added ccache to speed up the build process. It was intentional, not accidental.

**Comment by prahal** [comment]
@d1vanov so I thought. Thanks for the feedback.
So my fixup of the README will do to fix this issue (i.e. the README tells us to read the Dockerfile to find the build dependencies, but currently in the develop branch the README points to nowhere as the Dockerfile it points to has been removed). As the new Dockerfile I made the README points in my Pull request #212 has ccache in it, that will do.

Still, for completeness. Did you intend to intentionally speed up the docker builds or as you did speed up all `./development/build-with-qmake.sh` builds?

**Comment by d1vanov** [comment]
The latter, for all builds. Ccache is quite useful especially in situations when qmake actually changes the generated makefile somehow which triggers full rebuild of the project. With ccache this rebuild would be much faster than without it.

**Comment by prahal** [comment]
https://github.com/robert7/nixnote2/pull/212 has been merged in the develop branch in https://github.com/robert7/nixnote2/commit/e7ed12b5a1e339256080e455b84b0faa161a33b3, closing
