### ISSUE TITLE
Feature request: Wayland support & icu  74.2 lib

### ISSUE THREAD

**Issue by ansdim1** [robert7/nixnote2#221]
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: xcb.
I use "QT_QPA_PLATFORM=xcb"
2023-12-13: ICU 74.2 released https://icu.unicode.org/

**Comment by prahal** [comment]
nixnote2 does not depend directly on libicu. Probably a libqt5 dependency.
As far as I know, the wayland or xcb platform is managed by Qt, not the application. 

>  I use "QT_QPA_PLATFORM=xcb"
Do you mean that when you select xcb it works or that you get the wayland not supported when you ask for xcb (which would not make sense, but you say ` I use "QT_QPA_PLATFORM=xcb"` so maybe something weird is happening).

These are not nixnote2 issues, but qt5 ones.
Please close this bug if you are running under Xorg and you only get this could not find plugin wayland error when QT_QPA_PLATFORM=wayland. I do not have the permission to do so on my side.

**Comment by prahal** [comment]
ping? Could you test my above suggestion for nixnote2 wayland and close this issue if ok?

**Comment by ansdim1** [comment]
OK. Now I have no problem with nixnote2 + Hyprland v0.42.
