### ISSUE TITLE
"open dir error: Permission denied" with current appImage

### ISSUE THREAD

**Issue by vitaly-zdanevich** [robert7/nixnote2#225]

**Comment by robert7** [comment]
you need to provide more info..

**Comment by vitaly-zdanevich** [comment]
Download AppImage
chmod u+x
run
got error

**Comment by vitaly-zdanevich** [comment]
Oh but it works on my another computer...

**Comment by robert7** [comment]
no idea, but you can try some another random AppImage, to check whenever problem is in nixnote or somewhere else (e.g. operating system)

you can try e.g. this https://keepassxc.org/download/#linux

**Comment by vitaly-zdanevich** [comment]
Hm the same error...

**Comment by vitaly-zdanevich** [comment]
What folders NixNote trying to read? `~/.config/nixnote`?

**Comment by robert7** [comment]
If you get same error with another AppImage, then the problem likely isn;t in nixnote

To check what directories are accessed, you max run nixnote with high log level - see: https://github.com/robert7/nixnote2/wiki/HowTo---Change-logging-level

**Comment by vitaly-zdanevich** [comment]
Thanks, tried 1 and 0:

```
$ ./NixNote2-x86_64.AppImage --logLevel=1
open dir error: Permission denied
```

**Comment by robert7** [comment]
it seems the AppImage has not even started.

I guess due some condition on your local system. 

this could be relevant: https://forum.freecad.org/viewtopic.php?t=28516

else try to unpack the app image and then run

**Comment by prahal** [comment]
Likely you have both the setuid bit set on the appimage file and the appimage owned by root. But I don't know how it came to be.
Can you send the output of `ls -l <appimage file>`?

You could still check that the appimage has the execute bit set but you should get a shell error if not, lie:
`bash: ./FreeCAD-13519.glibc2.17-x86_64.AppImage: Permission denied`
Findings from:
"open dir error: Permission denied" seems pretty rare.
- https://www.reddit.com/r/Gentoo/comments/1djxkaz/cannot_run_any_appimage_open_dir_error_permission/ only gives a workaround that is to extract the appimage content.
- https://github.com/LizardByte/Sunshine/issues/2409#issuecomment-2057614092 which has the same error as you after he changed the ownership of the appimage to root and set the setuid bit on it.

Note that even with the setuid bit and root ownership if you do not have the execute bit set you  get the bash permission denied error, not the "open dir error: Permission denied".

**Comment by vitaly-zdanevich** [comment]
Now it starts, fixed by itself, I do not know why... thanks for the help.
