### ISSUE TITLE
Get link to note

### ISSUE THREAD

**Issue by MRC01** [robert7/nixnote2#24]
In the main app window note list, you can right-click any note and "Copy Note Link". Then you can paste that link into any other note. This is a useful feature to make notes refer to each other with hyperlinks.

However, this is the only way to get a note link, which makes some workflow difficult. For example, suppose you're working on 2 notes A and B each in their own separate windows (not the main app window), and you want to add to note B a link to note A. Note A is open right there in front of you, but you can't get its link. You must go to the Nixnote main app window (which might even be on a different desktop), get note A to appear in the note list (it might not be in the note list in which case you must search for it), then right click it and pick "Copy Note Link". Then go back to note B and paste the link.

It would be FAR simpler and quicker if we had a hotkey or button on the note editor toolbar for "Copy Note Link". In that case, you'd simply click this button for note A, then click note B and paste. No need to navigate back to the main app window, to get the note to appear in the note list, etc.

**Comment by MRC01** [comment]
OK, I'm looking into this, and adding a new hotkey for it.

**Comment by rodelrod** [comment]
Has this been fixed since? I can do Ctrl-Shift-k do get the note link from any window.

**Comment by MRC01** [comment]
Not that I know of. Ctrl+Shift+K doesn't do anything for me. And it's
not in shortcuts.txt.

**Comment by rodelrod** [comment]
I found out about it right-clicking on the note's body. Here's a screenshot (on version 2.1.0-beta-3-67ed083):
![tooltip_024](https://user-images.githubusercontent.com/1851908/49704233-a607b780-fc10-11e8-95d6-2a3272b60d9e.png)

**Comment by robert7** [comment]
@MRC01 
its `Edit_Copy_Note_Url            Ctrl+Shift+K      // Copy the current note URL to the clipboard`
I added this now as default (in 2.1.2-b).

**Comment by robert7** [comment]
@MRC01 pls recheck if it works as expected, so we can eventually close this.
Btw the function was actually there from beginning, I just didn't know myself :smile:

**Comment by MRC01** [comment]
I added that entry to shortcuts.txt in both locations: ~/.nixnote and
/usr/share/nixnote2. Either location alone should do it, but neither
works. The hotkey doesn't work. But the menu item is there, and works.

This is with version 2.1.1 from the repo.

**Comment by MRC01** [comment]
It loads shortcuts.txt in the right order (system first, then user):

DEBUG 2018-12-11 07:30:20.614 src/gui/shortcutkeys.cpp:37 About to load
system shortcuts from "/usr/share/nixnote2/shortcuts.txt"
DEBUG 2018-12-11 07:30:20.614 src/gui/shortcutkeys.cpp:48 Loading
"/usr/share/nixnote2/shortcuts.txt"
DEBUG 2018-12-11 07:30:20.614 src/gui/shortcutkeys.cpp:39 About to load
user shortcuts from "/home/mclement/.nixnote/shortcuts.txt"
DEBUG 2018-12-11 07:30:20.614 src/gui/shortcutkeys.cpp:48 Loading
"/home/mclement/.nixnote/shortcuts.txt"

Here's the line from my shortcuts.txt:

Edit_Copy_Note_Url            Ctrl+Shift+K      // Copy the current note
URL to the clipboard

But Nixnote is not picking up this shortcut. No errors or warnings, as
if it's ignoring it.

**Comment by robert7** [comment]
@MRC01 with the trace level logging (e.g. `./appdir/usr/bin/nixnote2 --logLevel=0  `)
you can now see in the log which key was set to what
you need to use the last version "2.1.2-d"

then the terminal output looks like
```
DEBUG 2018-12-11 18:01:51.007 src/gui/shortcutkeys.cpp:48 Loading "/d/dev/nixnote2/appdir/usr/share/nixnote2/shortcuts.txt"
TRACE 2018-12-11 18:01:51.008 src/gui/shortcutkeys.cpp:116 Removing by action "file_note_add"
TRACE 2018-12-11 18:01:51.008 src/gui/shortcutkeys.cpp:100 Setting "file_note_add" to "ctrl+n"
TRACE 2018-12-11 18:01:51.008 src/gui/shortcutkeys.cpp:116 Removing by action "file_note_reindex"
TRACE 2018-12-11 18:01:51.008 src/gui/shortcutkeys.cpp:116 Removing by action "file_note_modify_tags"
TRACE 2018-12-11 18:01:51.008 src/gui/shortcutkeys.cpp:116 Removing by action "file_note_delete"
TRACE 2018-12-11 18:01:51.008 src/gui/shortcutkeys.cpp:100 Setting "file_note_delete" to "ctrl+shift+d"
TRACE 2018-12-11 18:01:51.008 src/gui/shortcutkeys.cpp:116 Removing by action "file_note_restore"
..........

DEBUG 2018-12-11 18:01:51.018 src/gui/shortcutkeys.cpp:39 About to load user shortcuts from "/home/robert7/.nixnote/shortcuts.txt"
DEBUG 2018-12-11 18:01:51.018 src/gui/shortcutkeys.cpp:48 Loading "/home/robert7/.nixnote/shortcuts.txt"
TRACE 2018-12-11 18:01:51.018 src/gui/shortcutkeys.cpp:116 Removing by action "edit_html_simplify"
TRACE 2018-12-11 18:01:51.018 src/gui/shortcutkeys.cpp:107 Removing by shortcut "ctrl+space"
TRACE 2018-12-11 18:01:51.018 src/gui/shortcutkeys.cpp:100 Setting "edit_html_simplify" to "ctrl+space"
TRACE 2018-12-11 18:01:51.018 src/gui/shortcutkeys.cpp:116 Removing by action "edit_insert_hyperlink"
TRACE 2018-12-11 18:01:51.018 src/gui/shortcutkeys.cpp:107 Removing by shortcut "ctrl+k"
TRACE 2018-12-11 18:01:51.018 src/gui/shortcutkeys.cpp:100 Setting "edit_insert_hyperlink" to "ctrl+k"
TRACE 2018-12-11 18:01:51.018 src/gui/shortcutkeys.cpp:116 Removing by action "edit_insert_todo"
DEBUG 2018-12-11 18:01:51.044 src/global.cpp:923 Loading theme "Default"
```

then the key is `TRACE 2018-12-11 18:01:51.014 src/gui/shortcutkeys.cpp:100 Setting "edit_copy_note_url" to "ctrl+shift+k"`

note that in case you want to override the key, you don't need to copy the whole file shortcuts.txt to ~/.nixnote - just the lines you want to change

further, in case there is syntactic error, this will be ignored (as the parsing of the file is quite lame); but should work if you don't have any syntactic errors :smile:

**Comment by MRC01** [comment]
I deleted all lines from my local shortcuts.txt except the one that sets
the key for copy note link. so now it looks like this:

// standard shortcuts
// you may copy the file to ~/.nixnote and adjust keyboard mappings
Edit_Copy_Note_Url            Ctrl+Shift+K      // Copy the current note
URL to the clipboard

Now the shortcut works. This shouldn't have fixed it, but it did.

**Comment by robert7** [comment]
OK. With the last version ""2.1.2-d" the "Edit_Copy_Note_Url Ctrl+Shift+K" is already set as default... so you don't even need the customized shortcuts file

**Comment by MRC01** [comment]
This is nice. No need for me to add this feature, it's already there.

One remaining bug is that Nixnote occasionally crashes with a seg fault
saying something about a timer thread. I posted that stack trace here
somewhere as a bug. This is very rare, and only happens if I leave it
running on my laptop through a few suspend/wake cycles. I might try to
tackle that one.

Also, there's the reworking of search and click on column for sorting,
that we discussed in another thread.

The Nixnote Linux client is already very nice. With these changes it
would be near-perfect!

**Comment by robert7** [comment]
>One remaining bug is that Nixnote occasionally crashes with a seg fault
saying something about a timer thread

ok. doesn't happen to me. if you can pinpoint then describe it as new issue

yes. there are some issues open from you, i think.. i plan to improve the sorting
