### ISSUE TITLE
To have a saved search created todotxt formatted output as a query from the command line

### ISSUE THREAD

**Issue by timoc** [robert7/nixnote2#3]
Was pushupstream, which i realize you have been doing. 
Changing to a feature request - 
Consider Evernote/Nixnote2 as a Capture/Organise tool, a personal library of sorts. It is not designed to support the Doing phase. To address this i would like to be able to query evernote and generate todotxt output. 

Specifically:
To have a saved search created todotxt formatted output  as a query from the command line (and UI?)
so that something like:
```
nixnote2 todoquery <saved search> 
```
will generate a [todo.txt](http://todotxt.org/)  file, so that i can use it with my android clockworktomato and/or any other todo.txt system to support performing next actions.

**Comment by robert7** [comment]
Regarding pushing changes to upstream unfortunately this is currently not possible :(, as the original maintainer, can't be reached/doesn't currently respond ..

**Comment by timoc** [comment]
Yeh i found that out, directly after i suggested it.

**Comment by robert7** [comment]
I'm not using the "todo" features of Evernote, as I find them too simple/awkward.

I use other external tool and I haven't connected it to Evernote. For me, this is no problem, as in the "todo" app I only need few words per task and also most of them repeat at some intervals. So the sync with Evernote would not be trivial. (I'm using [OmniFocus](https://www.omnigroup.com/omnifocus/)). I'm more using it as "don't forget app" as a real "todo list"..

So given limit time I have for this project, any new developments concerning todo's have no big priority for me. But you are welcome to add it yourself, if you can... pull requests are welcome :) I could provide some hints, in case you want to implement it.

But you able to do some scripting, you could create some workaround solution for you.
1. export all notes containg todo's e.g. using `nixnote21 export --search="todo:false" --output=open-todos.nnex`
2. use some script written in any language you like (like python, awk, javascript, bash - what ever) to process the created xml file and convert it fo format of your need. The "todo's" are in the XML in `<en-todo>` tags..
