### ISSUE TITLE
Clicking "New Note" button creates two new notes

### ISSUE THREAD

**Issue by bedohave** [robert7/nixnote2#34]
**What I did**: clicked the New Note button in the NixNote ToolBar

**What I expected**: I would have a new note titled "Untitled note" and that my cursor would be in the body of that new note, ready for me to start writing.

**What happened**: I got _two_ notes titled "Untitled note" and my cursor was placed in the body of the top (most recent of the two?) note. 

When I use the keyboard shortcut (Ctrl-N), NixNote creates just one note.

I see this in both 2.1.0-beta4d and -beta4g. 

Not sure if this is related to fixed issue #8: https://github.com/robert7/nixnote2/issues/8

**Comment by robert7** [comment]
OK. I can reproduce. It will be fixed. Its funny, that I also got it occasionally, but always thought, that I someway clicked the "new note" twice.

**Comment by robert7** [comment]
@bedohave  this should be fixed in version 2.1.0-beta4h 
you can test it using the latest development AppImage https://github.com/robert7/nixnote2/releases/tag/continuous-develop
