### ISSUE TITLE
URL for latest AppImage

### ISSUE THREAD

**Issue by HaleTom** [robert7/nixnote2#36]
As my AUR build-from-source package is almost done I'm looking at creating a `-bin` package also.

My initial plan was to generate a URL from the latest annotated tag, but I notice there is no AppImage for `v2.1.0-beta4g`.

As there may be a lag in build after release, a `latest` URL would be preferred.

Is there a URL to to use download the latest available AppImage?

**Comment by robert7** [comment]
yes. as explained here: https://github.com/robert7/nixnote2/wiki/Releases---versions%2C-build-pipeline%2C-branches%2C-tags

the tip of the "master" branch gets "continuous" tag and is published here:
https://github.com/robert7/nixnote2/releases/tag/continuous

Currently the url of the AppImage itself currently changes with the version, but I already see, this is disadvantage. So I'll change that.

**Comment by HaleTom** [comment]
Thanks for the stable AppImage link :)

I finally got around to building a `nixnote2-appimage` via `PKGBUILD`.  Expect it in the Arch AUR soon.
