### ISSUE TITLE
Arch Linux package

### ISSUE THREAD

**Issue by HaleTom** [robert7/nixnote2#37]
The Arch Linux package I created is now live. May I suggest the following doco update:

```
## Packages
### Linux
#### Ubuntu
An Ubuntu PPA is available. See [here](https://github.com/robert7/nixnote2/wiki/NixNote-PPA) for details.

#### Arch Linux
AUR package [nixnote2-git](https://aur.archlinux.org/packages/nixnote2-git/) builds the latest stable release (HEAD from the `continuous` branch)
```

**Comment by robert7** [comment]
OK. Thank you very much. 
I'll update the readme later.

**Comment by robert7** [comment]
@HaleTom 
hi, there is still some problem with your packaging at https://aur.archlinux.org/packages/nixnote2-git/
see comment from ljubacanoa .. `make: /usr/bin/lrelease: Command not found`

I think there is missing dependency. No idea about Arch, but on Ubuntu the pkg name would be `qttools5-dev-tools`.

**Comment by HaleTom** [comment]
Thanks for the heads-up. I believe it is now fixed. It turned out I needed *both* `qt5-base` and `qt5-tools`.

While this issue is open... I'm looking into creating a `-bin` version of the package. 

I'd prefer to rip open the AppImage to not install 127MB of libraries which are already installed on the system.

The only issue I'm having is `libhunspell-1.3.so.0`. Arch has `/usr/lib/libhunspell-1.6.so.0` and I'd prefer not to install an older version.

Is there any way to link to just `libhunspell.so` which is generally a symlink to the current numbered version?

Also, any reason you don't `strip` the `nixnote2` executable to save about 120MB?

**Comment by robert7** [comment]
>Also, any reason you don't strip the nixnote2 executable to save about 120MB?

Ok.i'll recheck (although as the AppImage is compressed, this doesn't make so much difference in reality - althouth the binary is 120M the AppImage all together is 98M... but anyway i'll fix)

>I'd prefer to rip open the AppImage to not install 127MB of libraries which are already installed on the system.

I don't think this is good idea. You can use the AppImage 1:1 as it is - or optionally unpack it (in case you don't have FUSE installed), it should work out of the box on ArchLinux, but to "rip it" - you asking for unneeded problems. 

The whole idea of the AppImage is: that everything is includes - therefore eliminates the potential differences. This has of course drawback, that the binary is bigger - but I don't think the people today care whenever the binary is 10M or 98M. More important is, that it works.

>The only issue I'm having is libhunspell-1.3.so.0. Arch has /usr/lib/libhunspell-1.6.so.0 and I'd prefer not to install an older version.

I can't change that so easily and I won't. The AppImage is build with "Ubuntu Xenial 16.04" - and this is how it is there compiled.

If you want to build binary package for Arch Linux. I suggest to build from source. And then create binary pkg out of that build.  Sorry I have no idea how the packaging works on Arch Linux and I have no time to study it now..

**Comment by HaleTom** [comment]
Doh. I'll get on to it tomorrow morning. I appreciate your attention to detail. 

I found something about package checking the build deps in a chroot today. It seems I'll need to update their wiki on that best practice... It's the open source world... You get the world you build ;)

**Comment by robert7** [comment]
I added the missing "strip" - this actually makes a lot of difference (the AppImage is now 52M from former 98M). 
Thanks for pointing this out! The latest development build (beta-4i) already has the strip applied.

**Comment by robert7** [comment]
@HaleTom :
I got email suggesting that you should try to replace

`depends=(hunspell java-runtime hicolor-icon-theme poppler-qt5 tidy qt5-webkit)`
`makedepends=(git qt5-base qt5-tools)`
with
`depends=(opencv hunspell java-runtime hicolor-icon-theme poppler-qt5 tidy qt5-webkit)`
`makedepends=(git qt5-base qt5-tools boost)`

can't verif it now, but try :)

**Comment by HaleTom** [comment]
I worked out how to build in a chroot, got the correct makedepends and a user has confirmed that the package now builds correctly.

Cheers re `strip`.

**Comment by robert7** [comment]
perfect. thanks!
