### ISSUE TITLE
Ability to set default notebook for new notes

### ISSUE THREAD

**Issue by HaleTom** [robert7/nixnote2#39]
## Expected
I am able to set the default notebook for new notes (I type ^N).

and / or:

An option for "the notebook used to create the last note is selected to create the new note"

https://help.evernote.com/hc/en-us/articles/208314728-How-to-change-your-default-notebook

## Actual behavior
Notes are created in a random notebook. The same notebook is used to create all notes.

## Steps to reproduce the problem

Press ^N

## Specifications

Version: 2.1.0-beta4d-8f235769

**Comment by robert7** [comment]
Actually its there.. maybe a bit hidden :)
Right click on desired notebook, then click "Properties".

![screen_20181009_02](https://user-images.githubusercontent.com/1135218/46684540-63673600-cbf3-11e8-83ab-ba2563a9c33b.png)

**Comment by HaleTom** [comment]
Wonderful!!! Thank you!
