### ISSUE TITLE
Ability to bulk move notes

### ISSUE THREAD

**Issue by HaleTom** [robert7/nixnote2#40]
Due to #39, I realise that I have a bunch of notes in an undesired notebook.

Is there a way to bulk-move notes?

**Comment by robert7** [comment]
You should be able to to drag&drop between notebooks.

**Comment by robert7** [comment]
Select notes in the list (e.g. using Ctrl-click) then drag to desired notebook.. Confirm & close

**Comment by HaleTom** [comment]
Total PEBCAK. 
Thanks!
