### ISSUE TITLE
Running Nixnote causes closing all apps and reboot 

### ISSUE THREAD

**Issue by GriMel** [robert7/nixnote2#41]
This issue is related to https://github.com/baumgarr/nixnote2/issues/463

Same behaviour with this fork

[messages.log.zip](https://github.com/robert7/nixnote2/files/2466570/messages.log.zip)

**Comment by robert7** [comment]
ok. unfortunately I don't see any meaningful info in the log, which would hint about some cause.
I suggest following
1. download latest AppImage https://github.com/robert7/nixnote2/releases/tag/continuous-develop
this contains all the dependencies, so potential for problems is a bit smaller, then with the PPA version
you are using
2. mark the downloaded file as executable (e.g. `chmod +x NixNote2-x86_64.AppImage`)
3. then run `./NixNote2-x86_64.AppImage --configDir=$HOME/.nixnote2  --logLevel=1  >nixnote2-debug.log 2>&1`

This will create new config & data directory (in `$HOME/.nixnote2`) and you will start from scratch (need to login to Evernote etc..). In case it doesn't work, post the created file "nixnote2-debug.log".
In case it will work, then try again the PPA version using `nixnote2  --configDir=$HOME/.nixnote2  --logLevel=1`

**Comment by GriMel** [comment]
That worked! Thank you. One question though - should I always run nixnote as 

> nixnote2 --configDir=$HOME/.nixnote2 --logLevel=1

or now I can run it as always?

**Comment by robert7** [comment]
The command I used, caused creation of new config+data in `$HOME/.nixnote2`

Now you could delete the original config (as your data is in cloud anyway and newly in $HOME/.nixnote2). Using `rm -rf $HOME/.nixnote` you delete the original config - there could be something wrong with it.

Now you can move the temporary config into the default place `mv $HOME/.nixnote2 $HOME/.nixnote`

The you should be able to run normally by `nixnote2`.
Take care, that you remove the correct directory and eventually make a backup before..

**Comment by GriMel** [comment]
When I removed old config file and moved .nixnote2 to .nixnote and started nixnote2 from console - sync started from the scratch and when it ended - application crashed. When I was running AppImage - everything worked OK.

**Comment by robert7** [comment]
> sync had started again from the scratch

weird. it should simply continue where it was. not start from beginning

you can try following:
`nixnote2 --logLevel=1 >nixnote2-debug.log 2>&1` and the post the log, whenever there would be something about the crash...

Otherwise, if you found a working "workaround" (as you said previously it worked), then I'll suggest use that. It could be that some of the binary dependencies is wrong on your system. The AppImage has everything included - so there this possibility is minimized.
