### ISSUE TITLE
Attachments not showing correct icon until note refresh

### ISSUE THREAD

**Issue by msbentley** [robert7/nixnote2#45]
## Expected vs. actual behavior

Adding an attachment to a note used to show an icon reflecting its file-type and name immediately. Currently I get something like this:

![image](https://user-images.githubusercontent.com/1671065/47031842-1514e280-d171-11e8-8a66-f6dd1cfd09f6.png)

If I change to another note and back, the icon is restored.

## Steps to reproduce the problem (or [log file)

  1. Create a new note
  2. Drag in a new file (e.g. PDF) or use "Attach file"

## Specifications

Version: 2.1.0-beta4j~201810131046 ubuntu18.04.1

(installed from PPA)

**Comment by robert7** [comment]
Should be fixed in "2.1.0-beta4k" pls retest with the new development build (should be available in a while).

**Comment by msbentley** [comment]
I've just tested in version: 201810230718~2.1.0-beta4~ubuntu18.04.1 from the PPA, the it looks good there, thanks!
