### ISSUE TITLE
Improve/fix individual note encryption

### ISSUE THREAD

**Issue by robert7** [robert7/nixnote2#47]
Note encryption now works - with the older [Evernote 64 bit RC2 cipher](https://help.evernote.com/hc/en-us/articles/208314128-What-type-of-encryption-does-Evernote-use-) as it was implemented in V2.0.

What works:
* select part of the note and select "encrypt"
* sync & view encrypted content (both in Nixnote and Evernote web client) - read only
* to edit the content you need to select "decrypt permanently" - then edit & encrypt again

What doesn't work
* the html code handling in "permament decrypt" is a bit hacky, so it may not work 100% is the note more complex/html - so temporarily only use with plain text notes

TODO as improvement
* implement Evernote "AES - 128 bit" cipher
* improve stability

..as alternative it is also to [encrypt everything](https://github.com/robert7/nixnote2/wiki/Relocation-of-config-and-data-directory#encrypted-data-directory)

**Comment by notbeep** [comment]
Would be great to have support for whatever Encryption method the Evernote apps use by default (seems to be AES, as the decryption error says AES)
![screenshot evernote decrypt aes](https://user-images.githubusercontent.com/58862803/71549440-2dd27800-2972-11ea-9652-f01ee81b0eec.jpg)
