### ISSUE TITLE
build script not working on fedora

### ISSUE THREAD

**Issue by timoc** [robert7/nixnote2#5]
Fedora has qmake-qt5 and qmake-qt4 as possible options.
also ```qmake -query``` will tell you everything you need to know about the provided build environment for that version of QT's qmake

Can i suggest the first parameter of the script is the build type, and the second a path to the qmake binary for the qt you want to build against?

**Comment by robert7** [comment]
Don't understand what you mean.. :)

The build helper script `development/build-with-qmake.sh` already has 2 parameter: QT_DIR (param1) and BUILD_TYPE (param2).
So you already can pass in where qmake is..

**Comment by robert7** [comment]
But you are free to adjust the build script.. this is not really essential to the project.

**Comment by timoc** [comment]
the build script fails because even with QT_DIR set to usr, fedora uses the /usr/bin/qmake-qt5 and /usr/bin/qmake-qt4 to allow you to explicitly choose your qt qmake.

**Comment by robert7** [comment]
Then I suggest make a copy of the "build-with-qmake.sh" script, you can name it "build-with-qmake-fedora.sh" and adjust it. Should be trivial. As the script is just some supplementary helper. Or if you can make a version which can work on both (should be also easy), then improve it and post pull request.

You can also easily build without the build script. Its just a convenience helper. Just run the correct qmake and them make.

**Comment by robert7** [comment]
I updated the README in "development" in a way that those are just "convenience shortcuts"..

I also improved the docker build. So currently should should be able to do the build with one command from ~"any" distribution by just executing the one script (`./development/build-with-docker-xenial.sh`). 
Not yet merged in master, but will come with "v2.1 beta-3". This should also work on your Fedora :)
