### ISSUE TITLE
Sorting Notes by tags

### ISSUE THREAD

**Issue by krolloc1** [robert7/nixnote2#51]
Is it possible to sort notes by tags? In the older version of nixnote2 it could be done and was helpful when using the "Getting Things Done" method. Thank you for a great product.

**Comment by robert7** [comment]
No. Currently its not possible, but can be added quite easily.
I'm also using kind of "Getting Things Done" method (bit simplified by now; but not involving tags in Nixnote).

**Comment by krolloc1** [comment]
I appreciate the quick response. I use tags like "1-Now", "2-Next",..., and sort by tags to keep them in order. What simplified method do you use if you don't mind me asking? I'm all about simplicity.

Thank you for taking your time to even code this stuff. I know it takes a lot of time. I do some coding for my job so I know how it goes.

**Comment by robert7** [comment]
I added the sorting by "tags" in version 2.1.0-beta5a - https://github.com/robert7/nixnote2/wiki/HowTo---Test-latest-application-changes-using-development-version 

Regarding GDT - I did read the book (I think it was this one https://www.amazon.com/Getting-Things-Done-Stress-Free-Productivity/dp/0142000280 ), but it was years ago.. so I don't exactly remember what was in. E.g. after a while I skipped the recommended periodical "reviews" (although I do sometimes, but seldom 7 irregularly). Currently I'm using OmniFocus for iPhone - https://www.omnigroup.com/omnifocus/ 
There is also Android version (from different vendor), I did use it for a while.

Here is some article hot it works https://inside.omnifocus.com/gtd (but I don't have Mac so I stuck with whats available for the iPhone version).

It mainly helps me with repeated tasks - there a many simple tasks which I need to do one time a week or always on 5th in the month or 1x in quarter etc. Or you can say do task XY on next Tuesday at 14:00.. 
 The app notifies you, when its time to do the task. 
Usually task name its enough for me to know what to do (if I need more info, then of course I have it in Evernote :) ).

**Comment by robert7** [comment]
![screen_20181026_01](https://user-images.githubusercontent.com/1135218/47564558-b21c0c00-d925-11e8-8c42-c01293035881.png)

There are also further improvements in sorting planned: see https://github.com/robert7/nixnote2/issues/18

**Comment by krolloc1** [comment]
Thank you very much for enhancement and for the info on omnifocus. I really do appreciate it,
