### ISSUE TITLE
Warnings printed to terminal

### ISSUE THREAD

**Issue by HaleTom** [robert7/nixnote2#53]
## Expected vs. actual behavior
No warnings / errors appear

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))

  1. Run latest AppImage

I see:
```
ravi@svelte:~/code/aur/nixnote2-bin (attempt-extract*%)% ./NixNote2-x86_64.AppImage                                                                                                      214ms | 18-10-29 22:00:24
INFO  2018-10-29 22:00:29.029 src/utilities/crossmemorymapper.cpp:59 Shared memory segment allocated, instance key: "2408f847-abd6-4108-aa2b-e824cfd42ed01"
INFO  2018-10-29 22:00:29.031 src/main.cpp:287 NixNote 2.1.0-beta5a-923c88b, build at Oct 26 2018 at 08:54:25, with Qt 5.5.1 running on 5.5.1
INFO  2018-10-29 22:00:29.031 src/main.cpp:290 To get more detailed startup logging use --logLevel=1
Could not parse stylesheet of object 0x1eac6f0
Could not parse stylesheet of object 0x1eac6f0
Could not parse stylesheet of object 0x1eac6f0
INFO  2018-10-29 22:00:32.580 src/nixnote.cpp:205 encrypt available
Could not initialize OpenGL for RasterGLSurface, reverting to RasterSurface.
INFO  2018-10-29 22:00:52.030 src/main.cpp:357 Exit: retcode=0
ravi@svelte:~/code/aur/nixnote2-bin (attempt-extract*%)%                                                                                                                                 23.7s | 18-10-29 22:00:52
```

There are 4 `Could not` warnings.

## Specifications

Version: 2.1.0-beta5a-923c88b

**Comment by robert7** [comment]
Yes I know about. But currently it just kind of cosmetic issue. As far I know, it doesn't have any impact on application function.

**Comment by robert7** [comment]
I fixed the problem with `Could not parse stylesheet of object` in "2.1.0-beta5b" 

I don't get the message `Could not initialize OpenGL for RasterGLSurface, reverting to RasterSurface`. But I don't think it is anything of importance.

If I start the native package (not AppImage) I get additional warning `libpng warning: iCCP: known incorrect sRGB profile`... I'll check that later.
