### ISSUE TITLE
Interrupt with floating point exception

### ISSUE THREAD

**Issue by cnwangjie** [robert7/nixnote2#55]
Thank you for your work in a long term. But it still cannot work well. It will interrupt in a few seconds after login.

Following is last some logs before interrupt.

<details>

```
DEBUG 2018-11-07 19:34:32.254 src/nixnote.cpp:1640 Refreshing data
DEBUG 2018-11-07 19:34:32.255 src/gui/ntableview.cpp:492 Valid LIDs retrieved.  Refreshing selection
DEBUG 2018-11-07 19:34:32.255 src/models/notemodel.cpp:62 Sort order: "order by relevance desc, dateUpdated desc"                                                                                                   
DEBUG 2018-11-07 19:34:32.255 src/models/notemodel.cpp:231 Performing NoteModel select "SELECT \"lid\", \"dateCreated\", \"dateUpdated\", \"title\", \"notebookLid\", \"notebook\", \"tags\", \"author\", \"dateSubject\", \"dateDeleted\", \"source\", \"sourceUrl\", \"sourceApplication\", \"latitude\", \"longitude\", \"altitude\", \"hasEncryption\", \"hasTodo\", \"isDirty\", \"size\", \"reminderOrder\", \"reminderTime\", \"reminderDoneTime\", \"isPinned\", \"titleColor\", \"thumbnail\", \"relevance\" FROM NoteTableV WHERE lid in (select lid from filter) order by relevance desc, dateUpdated desc"                                        
DEBUG 2018-11-07 19:34:32.256 src/models/notemodel.cpp:62 Sort order: "order by relevance desc, dateUpdated desc"                                                                                                   
DEBUG 2018-11-07 19:34:32.257 src/gui/lineedit.cpp:139 Search got setFocus
DEBUG 2018-11-07 19:34:32.258 src/gui/lineedit.cpp:131 Search got focusInEvent
DEBUG 2018-11-07 19:34:32.262 src/gui/nbrowserwindow.cpp:634 Setting read only flag to=true, lid=-1
DEBUG 2018-11-07 19:34:32.768 src/nixnote.cpp:1616 starting NixNote::updateSelectionCriteria() filtercnt=11 pos=10                                                                                                  
DEBUG 2018-11-07 19:34:32.769 src/gui/nbrowserwindow.cpp:873 saveNoteContent() not dirty
DEBUG 2018-11-07 19:34:32.770 src/filters/filterengine.cpp:168 Purging filters
DEBUG 2018-11-07 19:34:32.773 src/filters/filterengine.cpp:170 Resetting filter table
DEBUG 2018-11-07 19:34:32.776 src/filters/filterengine.cpp:177 Reset complete
DEBUG 2018-11-07 19:34:32.776 src/filters/filterengine.cpp:188 Filtering favorite
DEBUG 2018-11-07 19:34:32.776 src/filters/filterengine.cpp:190 Filtering notebooks
DEBUG 2018-11-07 19:34:32.792 src/filters/filterengine.cpp:192 Filtering tags
DEBUG 2018-11-07 19:34:32.792 src/filters/filterengine.cpp:194 Filtering trash
DEBUG 2018-11-07 19:34:32.795 src/filters/filterengine.cpp:196 Filtering search string
DEBUG 2018-11-07 19:34:32.796 src/filters/filterengine.cpp:198 Filtering attributes
DEBUG 2018-11-07 19:34:32.796 src/filters/filterengine.cpp:200 Filtering complete
DEBUG 2018-11-07 19:34:32.805 src/nixnote.cpp:1640 Refreshing data
DEBUG 2018-11-07 19:34:32.806 src/gui/ntableview.cpp:492 Valid LIDs retrieved.  Refreshing selection
DEBUG 2018-11-07 19:34:32.806 src/models/notemodel.cpp:62 Sort order: "order by relevance desc, dateUpdated desc"                                                                                                   
DEBUG 2018-11-07 19:34:32.806 src/models/notemodel.cpp:231 Performing NoteModel select "SELECT \"lid\", \"dateCreated\", \"dateUpdated\", \"title\", \"notebookLid\", \"notebook\", \"tags\", \"author\", \"dateSubject\", \"dateDeleted\", \"source\", \"sourceUrl\", \"sourceApplication\", \"latitude\", \"longitude\", \"altitude\", \"hasEncryption\", \"hasTodo\", \"isDirty\", \"size\", \"reminderOrder\", \"reminderTime\", \"reminderDoneTime\", \"isPinned\", \"titleColor\", \"thumbnail\", \"relevance\" FROM NoteTableV WHERE lid in (select lid from filter) order by relevance desc, dateUpdated desc"                                        
DEBUG 2018-11-07 19:34:32.806 src/models/notemodel.cpp:62 Sort order: "order by relevance desc, dateUpdated desc"                                                                                                   
DEBUG 2018-11-07 19:34:32.808 src/gui/ntableview.cpp:826 Selecting row 0lid: 210
DEBUG 2018-11-07 19:34:32.809 src/gui/lineedit.cpp:139 Search got setFocus
DEBUG 2018-11-07 19:34:32.810 src/gui/lineedit.cpp:131 Search got focusInEvent
DEBUG 2018-11-07 19:34:32.813 src/gui/nbrowserwindow.cpp:426 Setting note contents to lid=210
DEBUG 2018-11-07 19:34:32.813 src/gui/nbrowserwindow.cpp:438 Current editor lid=-1, changing to lid=210
DEBUG 2018-11-07 19:34:32.814 src/gui/nbrowserwindow.cpp:453 ===== Loading note contents, lid=210
DEBUG 2018-11-07 19:34:32.814 src/gui/nbrowserwindow.cpp:461 Getting note, lid=210
DEBUG 2018-11-07 19:34:32.817 src/gui/nbrowserwindow.cpp:479 Checking if note is in cache, lid=210
DEBUG 2018-11-07 19:34:32.817 src/gui/nbrowserwindow.cpp:495 Note not in cache, lid=210
DEBUG 2018-11-07 19:34:32.817 src/gui/nbrowserwindow.cpp:503 Rebuilding note HTML, lid=210
DEBUG 2018-11-07 19:34:32.817 src/html/noteformatter.cpp:132 htmlfmt: rebuilding note HTML, note guid="34e4418d-b1a1-45de-b575-ea8dd07f65a2"                                                                        
DEBUG 2018-11-07 19:34:32.817 src/html/noteformatter.cpp:143 htmlfmt: getting resource from note guid="34e4418d-b1a1-45de-b575-ea8dd07f65a2"                                                                        
DEBUG 2018-11-07 19:34:32.819 src/html/noteformatter.cpp:148 Attachment: #19 "html-34e4418d-b1a1-45de-b575-ea8dd07f65a2-original-enml.xml"                                                                          
[1]    13614 floating point exception (core dumped)  NixNote-2.1.0-beta-2-x86_64.AppImage
```

</details>

### Reproduce steps:

 - Creating an account with yinxiang server
 - Authorizing success
 - Waiting for downloading the data

**Comment by robert7** [comment]
Hi
unfortunately I can't reproduce... see screenshot from latest AppImage build with yinxiang server
![screen_20181107_01](https://user-images.githubusercontent.com/1135218/48137219-dc64b680-e2a1-11e8-8023-dbc7f34f38dd.png)

I have following suggestions:
* first make sure you use latest stable build - [2.0.1](https://github.com/robert7/nixnote2/releases/download/v2.1.0/NixNote2-x86_64.AppImage) - as the name you quoted seems to be "2.0.1-beta-2" which would be quite old
* pls include whole log file (as zip), this contains version, which is then less ambiguous
* which linux distribution/version are you? 
  * in case its Arch Linux - are you able to try the build from source? https://aur.archlinux.org/packages/nixnote2-git/

The problem could be caused by some particular note you have. I've seen one very rare case where the AppImage build failed with "floating point" which was caused by a Qt bug. The current AppImage builds against Qt 5.5 which is pretty old.

**Comment by robert7** [comment]
In case you can reproduce "floating point" fail with the latest AppImage from releases (version Version: 2.1.0-a7c53be), then you can try the experimental build from https://www.dropbox.com/sh/bropykm64u8zdmv/AABmCL47YtUXglFMRnTFNnfia?dl=0 - NixNote2_2.1.0-QT56-x86_64.AppImage
This is same version as on releases but build against Qt 5.6

**Comment by robert7** [comment]
>I downloaded the latest build from the release page before but it still displays version 2.1.0-beta-2

No. this should not. 
Pls retry download: https://github.com/robert7/nixnote2/releases/download/v2.1.0/NixNote2-x86_64.AppImage
it should be have md5 sum: 2a28eadf64c1d3b86fa2b9b31b85ebc6
see screenshoot - in log and in "Help/About" it should display:  NixNote 2.1.0-a7c53be

![screen_20181108_01](https://user-images.githubusercontent.com/1135218/48186135-690d8400-e337-11e8-891d-ae6bc03e151d.png)

Then I would appreciate, if you could check, whenever you can reproduce the "floating point error" with the experimental AppImga build with Qt 5.6: https://www.dropbox.com/sh/bropykm64u8zdmv/AABmCL47YtUXglFMRnTFNnfia?dl=0 - NixNote2_2.1.0-QT56-x86_64.AppImage

**Comment by robert7** [comment]
OK thanks

**Comment by jbrains** [comment]
I had the same symptom and the Qt 5.6 build appears to work better for me now. Is there any information that I can give you about my system that would help you?

**Comment by robert7** [comment]
@jbrains: no. more info not needed now. It seems to be a problem of Qt 5.5. The AppImage uses this. I plan to build the AppImage with never version of Qt - but its a bit tricky because WebKit isn't available anymore in Qt >5.5 (there is a workaroung using community version of WebKit - https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-Linux). Unfortunately update of NixNote to use "WebEngine" module, isn't that trivial..

Meanwhile I suggest either use the AppImage with the Qt5.6 I provided, or you may try to build from source .

**Comment by jbrains** [comment]
I haven't seen any further problems, so I'm happy for now, and I wish you good luck in moving from WebKit to WebEngine. Thank you for providing a really helpful client!

**Comment by robert7** [comment]
Reopened as some users can still experience the problem... I plan to update the AppImage to be build with newer Qt then 5.5 ..

**Comment by robert7** [comment]
Experimental AppImage build of v2.1.2 with Qt 5.11 is available at: https://github.com/robert7/nixnote2/releases/download/v2.1.2/NixNote2-qt511-x86_64.AppImage for the use cases where the standard build (Qt 5.5) doesn't work because of specific Qt bugs.
