### ISSUE TITLE
Attachments cannot be opened by associated applications.

### ISSUE THREAD

**Issue by swordgreen** [robert7/nixnote2#57]
## Expected vs. actual behavior
When I click an attachment in a note, I hope the attachment will be opened by an associated software application that registered in the system. But in nixnote2, all attachments are associated with Thunderbird mail application except PDF files and Images.

How can I define preferred applications for different types of files in Nixnote2? 

## Specifications
I am using Version: 201811061734~2.1.0~ubuntu16.04.1 installed from PPA.

**Comment by robert7** [comment]
Hi,
I checked the source code, NixNote doesn't have any logic regarding file associations. The attachment file is simply stored on local disk (as local file), then Qt function [QDesktopServices::openUrl](http://doc.qt.io/archives/qt-4.8/qdesktopservices.html#openUrl) is called with the local file.

This is from the docs:

>Opens the given url in the appropriate Web browser for the user's desktop environment, and returns true if successful; otherwise returns false. If the URL is a reference to a local file (i.e., the URL scheme is "file") then it will be opened with a suitable application instead of a Web browser.

So basically operating system defaults apply. I did some further checks on Ubuntu 18.04 with the app installed from PPA... I created sample Office Writer file... this opens same way from Nautilus and from Nixnote.

Screenshoots:
![attach1-screen_20181115_03](https://user-images.githubusercontent.com/1135218/48624393-98159c80-e9ac-11e8-8299-20c76927bdd4.png)
![attach2-screen_20181115_02](https://user-images.githubusercontent.com/1135218/48624394-98159c80-e9ac-11e8-9f36-02b08257f5e9.png)
![attach3-screen_20181115_04](https://user-images.githubusercontent.com/1135218/48624395-98159c80-e9ac-11e8-8d1d-8c4de9c7ca0d.png)
![attach4-screen_20181115_04](https://user-images.githubusercontent.com/1135218/48624396-98159c80-e9ac-11e8-87ab-fc0feb9d38c0.png)

So I suggest check file associations on your operating system. You can compare what opens on particular local file with file manager and what opens on NixNote. Should be the same.
