### ISSUE TITLE
Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [robert7/nixnote2#58]
Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6.

## Expected vs. actual behavior

```
libstdc++.so.6: version `GLIBCXX_3.4.21' not found. 
```

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))

  1. Download the Ubuntu 14.04 Live ISO (the oldest still-supported version)
  1. Download the nixnote2 AppImage
  1. Try to run

## Specifications

  - c9acb4e AppImage

## References
  - https://travis-ci.org/AppImage/appimage.github.io/builds/459189832#L614 (test log)
  - https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6
  - https://github.com/AppImage/appimage.github.io/pull/844

**Comment by robert7** [comment]
:) ... yes I know of course. There is some minor compilation problem on Ubuntu 14.04. I could fix it, but as Trusty has only ~5 months until "end of life"... I considered it not worth the effort (as my time for this project is pretty limited).

This is also reason why I did not posted the AppImage to the central repository.. as there is a condition, that it should run on 14.04.
I'm not sure if this is real issue for real users of the application.

And there are other problems related to AppImage build which have higher priority.. Example: https://github.com/robert7/nixnote2/issues/55

**Comment by robert7** [comment]
I'll close this for now. If anyone is interested to contribute the fix for 14.04 - pull requests welcome :)
Else it should  become obsolete April 2019.
