### ISSUE TITLE
Default installation will also copy .java source files

### ISSUE THREAD

**Issue by hosiet** [robert7/nixnote2#61]
## Expected vs. actual behavior

It is expected that only the built `.jar` file is installed into the system. However, as in
https://github.com/robert7/nixnote2/blob/master/nixnote2.pro#L485 ,
current implementation is to install all the subdir, regardless whether it is the source code or the .jar file.

**Comment by robert7** [comment]
This is now fixed in develop branch. I'll do few more tests and merge it to "master".
