### ISSUE TITLE
Icon installed by default might be of too low resolution

### ISSUE THREAD

**Issue by hosiet** [robert7/nixnote2#62]
I noticed that nixnote 2.1 is using a new icon. However, the icon installed into system is a 48x48 png file:

```
./usr/share/icons/hicolor/48x48/apps/nixnote2.png
```

We may need some better icons (128x128, 256x256 or even higher). It would be ideal if there's also a SVG icon.

**Comment by robert7** [comment]
OK. I'll improve that

**Comment by robert7** [comment]
I added 128px, 256px and SVG icons..
