### ISSUE TITLE
Use new qevercloud version (new Evernote API)

### ISSUE THREAD

**Issue by hosiet** [robert7/nixnote2#63]
The core library to interact with Evernote cloud service should be [qevercloud](https://github.com/d1vanov/QEverCloud), which is currently embedded into nixnote2 source repository. Perhaps we should consider using new releases of qevercloud (qevercloud 4.x) to make use of Evernote API 1.28.

**Comment by robert7** [comment]
Yes I know about, but I'm not sure how much work this would be and basically everything works now how it is (with the old embedded  "qevercloud").

Changing it is against the basic software development rule: [ain't broke, don't fix](https://en.wiktionary.org/wiki/if_it_ain%27t_broke,_don%27t_fix_it#English) :)

But I'll keep the issue open, I could eventually do it. Mainly if something breaks down and the old API would not work anymore..

**Comment by robert7** [comment]
Hi @hosiet ,
I did update to newest [qevercloud 4.0](https://github.com/d1vanov/QEverCloud) (Evernote API 1.28) in Nixnote version  2.1.4-c.

Although it is still embedded into nixnote2 source repository and I don't currently  plan to change it to use shared library.
I understand shared library would be better, but it introduces a lot of problems and my time for this project is currently very limited.

**Comment by robert7** [comment]
But as usual... if anyone is willing to contribute a better setup... pull requests are always welcomed..
