### ISSUE TITLE
(Wrongly) recorded upstream changelog in /debian/changelog

### ISSUE THREAD

**Issue by hosiet** [robert7/nixnote2#64]
Oops. I know that Debian's changelog format can be attractive, but putting upstream changelog at the exact position as Debian's (`debian/changelog`) can be troublesome for downstream package maintainers. Could you please consider not making `changelog.txt` a symlink to `debian/changelog`?

**Comment by robert7** [comment]
I need the file "debian/changelog" for the PPA build... I wanted to avoid having extra repository just for packaging. Actually I have one: https://github.com/robert7/nixnote2-packaging - but I wanted to avoid having the code in the source repository and the changelog in "packaging repository".

I created addional symlink "changelog.txt" => "debian/changelog" - then symlink is not important - I can easily remove it - would that be enough? (FIX1)

Further what I could do would be make "changelog.txt" a copy of "debian/changelog" (FIX2) - then the same file would be inside twice. This would be sub-optimal/redundant - but I could live with that. What I would like to really avoid is to change (again) the recipe for PPA.

**Comment by robert7** [comment]
update: I did the "FIX2" - so now the "changelog.txt" contains the text. pls confirm its OK now.
(The "debian/changelog" is still present in the repository and it is copy of "changelog.txt")

**Comment by hosiet** [comment]
Yes, that helps a lot. Thanks!
