### ISSUE TITLE
Make project cross-buildable

### ISSUE THREAD

**Issue by hosiet** [robert7/nixnote2#67]
Downstream bug report: https://bugs.debian.org/915590

> [...]
> nixnote2 fails to cross build from source, because it strips with the
> wrong strip at the end of the build. Doing so breaks
>  * cross compilation, because it fails for the wrong architecture,
> [...]
> After replacing it with $$QMAKE_STRIP, this step is skipped for Debian
> as dh_auto_configure passes QMAKE_STRIP=: and therefore cross building a
> -dbgsym package works. Please consider applying it.

```diff
--- nixnote2-2.1.1~git20181202.orig/nixnote2.pro
+++ nixnote2-2.1.1~git20181202/nixnote2.pro
@@ -32,7 +32,7 @@
     DESTDIR = qmake-build-release
     BUILD_TYPE = release
     message($$TARGET: Release build!)
-    QMAKE_POST_LINK=strip $${DESTDIR}/$${TARGET}
+    QMAKE_POST_LINK=$$QMAKE_STRIP $${DESTDIR}/$${TARGET}
 }
 OBJECTS_DIR = $${DESTDIR}
 MOC_DIR = $${DESTDIR}
```

**Comment by robert7** [comment]
I applied the patch.
thanks for reporting!
