### ISSUE TITLE
Question about "Exits" tab in preferences

### ISSUE THREAD

**Issue by hosiet** [robert7/nixnote2#68]
I'm not sure what "Exit Behaviour" is when encountered it while translating:

![default](https://user-images.githubusercontent.com/8443926/49825728-1f0f2800-fd53-11e8-8d8a-904df274cc61.png)

...and I don't really know how to translate them.

Is there any documentation for it? Maybe we should add more explanations for this feature.

**Comment by robert7** [comment]
There is a description in the last announce email from the original author:
https://sourceforge.net/p/nevernote/mailman/nevernote-announce/?viewmonth=201707

there is also further description in the "Legacy Documentation" which I copied in wiki from the upstream project
https://github.com/robert7/nixnote2/wiki/Legacy-Documentation#exits
(original source of the legacy docs: https://github.com/baumgarr/nixnote2/tree/master/help )

I personally don't use it, didn't even tried it, but it could be useful for "power users" 

maybe I could add a hyperlink to the Preference Dialog tab..

**Comment by robert7** [comment]
So I looked at the functionality, it does work and actually could be useful in some use cases.
I restored the "sample_exits" from upstream repository (which are examples from original author).
Added wiki page with some description and links & button on the Preferences page.

https://github.com/robert7/nixnote2/wiki/Scripting-(Exits)
