### ISSUE TITLE
Let's eliminate dependency on Java, or should we?

### ISSUE THREAD

**Issue by hosiet** [robert7/nixnote2#69]
It's strange that a C++ project is bundling a .java file for encryption / decryption functions. I'm wondering if we could just remove everything under `/java` directory while keeps the original functionality of nixnote2 untouched.

**Comment by robert7** [comment]
Yes I know its weird. Was not my idea :)

I already created a issue for encryption improvement: https://github.com/robert7/nixnote2/issues/47
There is a C++ implementation of Evernote encryption in [Quentier](https://github.com/d1vanov/quentier) project incl. Evernote "AES - 128 bit" cipher - it is GPL so I plan to look, if I could copy it to Nixnote..

**Comment by robert7** [comment]
I'm closing this as it is duplicate. But I will improve encryption solution, when I find a bit time.
