### ISSUE TITLE
Unexpectedly closes after manually starting a sync with segment fault. 

### ISSUE THREAD

**Issue by terrell-r** [robert7/nixnote2#73]
Nixnote 

Unexpectedly closes after manually starting a sync with segment fault. 

## Specifications
Version: 201812162017~2.1.2-e~ubuntu18.04.1
 
Logs: 
messages.log: 
DEBUG 2018-12-28 13:45:52.304 src/utilities/noteindexer.cpp:120 Fetching resource for index using "syncrunner"
DEBUG 2018-12-28 13:45:52.314 src/utilities/noteindexer.cpp:128 Deleting old resource from index
DEBUG 2018-12-28 13:45:52.589 src/utilities/noteindexer.cpp:133 Adding attributes to index.
"Error: Couldn't find trailer dictionary"
"Error: Invalid XRef entry"
"Error: Invalid XRef entry"
"Error: Top-level pages object is wrong type (null)"
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = nixnote2 path = /usr/bin pid = 55967
KCrash: Arguments: /usr/bin/nixnote2 --logLevel=1 
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi from kdeinit
QSocketNotifier: Invalid socket 6 and type 'Read', disabling...
QSocketNotifier: Invalid socket 35 and type 'Read', disabling...
QSocketNotifier: Invalid socket 34 and type 'Read', disabling...

nQSocketNotifier: Invalid socket 8 and type 'Read', disabling...
QSocketNotifier: Invalid socket 22 and type 'Read', disabling...
QSocketNotifier: Invalid socket 41 and type 'Read', disabling...
QSocketNotifier: Invalid socket 20 and type 'Read', disabling...

OS Crash Output: 

Application: nixnote2 (nixnote2), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f313e5b0900 (LWP 56462))]

Crash Report: 

Thread 18 (Thread 0x7f30a8ff9700 (LWP 58821)):
#0  0x00007f31377a1bf9 in __GI___poll (fds=0x7f308c00aee0, nfds=1, timeout=112809) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f3130e4f539 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f3130e4f64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f31382f404b in QEventDispatcherGlib::processEvents (this=0x7f308c00c010, flags=...) at kernel/qeventdispatcher_glib.cpp:424
#4  0x00007f313829830a in QEventLoop::exec (this=this@entry=0x7f30a8ff8ca0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:214
#5  0x00007f31380c3bba in QThread::exec (this=<optimized out>) at thread/qthread.cpp:525
#6  0x00007f31380ceadb in QThreadPrivate::start (arg=0x7f30fc05b7e0) at thread/qthread_unix.cpp:367
#7  0x00007f31357cb6db in start_thread (arg=0x7f30a8ff9700) at pthread_create.c:463
#8  0x00007f31377ae88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 17 (Thread 0x7f3081c1c700 (LWP 58819)):
#0  0x00007f3130e95064 in g_mutex_unlock () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f3130e4eec8 in g_main_context_check () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f3130e4f4e0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f3130e4f64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f31382f404b in QEventDispatcherGlib::processEvents (this=0x7f3074004b60, flags=...) at kernel/qeventdispatcher_glib.cpp:424
#5  0x00007f313829830a in QEventLoop::exec (this=this@entry=0x7f3081c1bca0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:214
#6  0x00007f31380c3bba in QThread::exec (this=<optimized out>) at thread/qthread.cpp:525
#7  0x00007f31380ceadb in QThreadPrivate::start (arg=0x558ab03e7bf0) at thread/qthread_unix.cpp:367
#8  0x00007f31357cb6db in start_thread (arg=0x7f3081c1c700) at pthread_create.c:463
#9  0x00007f31377ae88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 16 (Thread 0x7f30a97fa700 (LWP 56616)):
#0  0x00007f3130e95049 in g_mutex_lock () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f3130e4f638 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f31382f404b in QEventDispatcherGlib::processEvents (this=0x7f3088008d00, flags=...) at kernel/qeventdispatcher_glib.cpp:424
#3  0x00007f313829830a in QEventLoop::exec (this=this@entry=0x7f30a97f9ca0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:214
#4  0x00007f31380c3bba in QThread::exec (this=<optimized out>) at thread/qthread.cpp:525
#5  0x00007f31380ceadb in QThreadPrivate::start (arg=0x558ab13f55e0) at thread/qthread_unix.cpp:367
#6  0x00007f31357cb6db in start_thread (arg=0x7f30a97fa700) at pthread_create.c:463
#7  0x00007f31377ae88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 15 (Thread 0x7f30a9ffb700 (LWP 56611)):
#0  0x00007f31357d19f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f3124ecd058) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7f3124ecd008, cond=0x7f3124ecd030) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7f3124ecd030, mutex=0x7f3124ecd008) at pthread_cond_wait.c:655
#3  0x00007f3137d4d79c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f313aac3407 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#5  0x00007f313aac1c2f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#6  0x00007f313aac1d06 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#7  0x00007f313aac5c78 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#8  0x00007f313aaea01a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#9  0x00007f31357cb6db in start_thread (arg=0x7f30a9ffb700) at pthread_create.c:463
#10 0x00007f31377ae88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 14 (Thread 0x7f30aa7fc700 (LWP 56610)):
#0  0x00007f31357d19f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f3124f05058) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7f3124f05008, cond=0x7f3124f05030) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7f3124f05030, mutex=0x7f3124f05008) at pthread_cond_wait.c:655
#3  0x00007f3137d4d79c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f313aac3407 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#5  0x00007f313aac1c2f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#6  0x00007f313aac1d06 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#7  0x00007f313aac5c78 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#8  0x00007f313aaea01a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#9  0x00007f31357cb6db in start_thread (arg=0x7f30aa7fc700) at pthread_create.c:463
#10 0x00007f31377ae88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 13 (Thread 0x7f30aaffd700 (LWP 56609)):
#0  0x00007f31357d19f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f3124eca058) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7f3124eca008, cond=0x7f3124eca030) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7f3124eca030, mutex=0x7f3124eca008) at pthread_cond_wait.c:655
#3  0x00007f3137d4d79c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f313aac3407 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#5  0x00007f313aac1c2f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#6  0x00007f313aac1d06 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#7  0x00007f313aac5c78 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#8  0x00007f313aaea01a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#9  0x00007f31357cb6db in start_thread (arg=0x7f30aaffd700) at pthread_create.c:463
#10 0x00007f31377ae88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 12 (Thread 0x7f30ab7fe700 (LWP 56608)):
#0  0x00007f31357d19f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f3124ec005c) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7f3124ec0008, cond=0x7f3124ec0030) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7f3124ec0030, mutex=0x7f3124ec0008) at pthread_cond_wait.c:655
#3  0x00007f3137d4d79c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f313aac3407 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#5  0x00007f313aac1c2f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#6  0x00007f313aac1d06 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#7  0x00007f313aac5c78 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#8  0x00007f313aaea01a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#9  0x00007f31357cb6db in start_thread (arg=0x7f30ab7fe700) at pthread_create.c:463
#10 0x00007f31377ae88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 11 (Thread 0x7f30abfff700 (LWP 56607)):
#0  0x00007f31357d19f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f3124ecb058) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7f3124ecb008, cond=0x7f3124ecb030) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7f3124ecb030, mutex=0x7f3124ecb008) at pthread_cond_wait.c:655
#3  0x00007f3137d4d79c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f313aac3407 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#5  0x00007f313aac1c2f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#6  0x00007f313aac1d06 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#7  0x00007f313aac5c78 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#8  0x00007f313aaea01a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#9  0x00007f31357cb6db in start_thread (arg=0x7f30abfff700) at pthread_create.c:463
#10 0x00007f31377ae88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 10 (Thread 0x7f30b0ea8700 (LWP 56606)):
#0  0x00007f31357d19f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f3124ff267c) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7f3124ff2628, cond=0x7f3124ff2650) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7f3124ff2650, mutex=0x7f3124ff2628) at pthread_cond_wait.c:655
#3  0x00007f3137d4d79c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f313aac3407 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#5  0x00007f313aac1c2f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#6  0x00007f313aac1d06 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#7  0x00007f313aac5c78 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#8  0x00007f313aaea01a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#9  0x00007f31357cb6db in start_thread (arg=0x7f30b0ea8700) at pthread_create.c:463
#10 0x00007f31377ae88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 9 (Thread 0x7f30f9fff700 (LWP 56470)):
#0  0x00007f313779d0b4 in __GI___libc_read (fd=20, buf=0x7f30f9ffea90, nbytes=16) at ../sysdeps/unix/sysv/linux/read.c:27
#1  0x00007f3130e93cd0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f3130e4f027 in g_main_context_check () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f3130e4f4e0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f3130e4f64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f31382f404b in QEventDispatcherGlib::processEvents (this=0x7f30ac000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:424
#6  0x00007f313829830a in QEventLoop::exec (this=this@entry=0x7f30f9ffeca0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:214
#7  0x00007f31380c3bba in QThread::exec (this=<optimized out>) at thread/qthread.cpp:525
#8  0x00007f31380ceadb in QThreadPrivate::start (arg=0x558ab06e0070) at thread/qthread_unix.cpp:367
#9  0x00007f31357cb6db in start_thread (arg=0x7f30f9fff700) at pthread_create.c:463
#10 0x00007f31377ae88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7f30fbe8b700 (LWP 56469)):
#0  0x00007f31377a1bf9 in __GI___poll (fds=0x7f30f4004a70, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f3130e4f539 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f3130e4f64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f31382f404b in QEventDispatcherGlib::processEvents (this=0x7f30f4000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:424
#4  0x00007f313829830a in QEventLoop::exec (this=this@entry=0x7f30fbe8aca0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:214
#5  0x00007f31380c3bba in QThread::exec (this=<optimized out>) at thread/qthread.cpp:525
#6  0x00007f31380ceadb in QThreadPrivate::start (arg=0x558ab057e250) at thread/qthread_unix.cpp:367
#7  0x00007f31357cb6db in start_thread (arg=0x7f30fbe8b700) at pthread_create.c:463
#8  0x00007f31377ae88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7f310a7e5700 (LWP 56468)):
#0  0x00007f31377a1bf9 in __GI___poll (fds=0x7f3100004e50, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f3130e4f539 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f3130e4f64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f31382f404b in QEventDispatcherGlib::processEvents (this=0x7f3100000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:424
#4  0x00007f313829830a in QEventLoop::exec (this=this@entry=0x7f310a7e4ca0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:214
#5  0x00007f31380c3bba in QThread::exec (this=<optimized out>) at thread/qthread.cpp:525
#6  0x00007f31380ceadb in QThreadPrivate::start (arg=0x558aafd043c0) at thread/qthread_unix.cpp:367
#7  0x00007f31357cb6db in start_thread (arg=0x7f310a7e5700) at pthread_create.c:463
#8  0x00007f31377ae88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7f310afe6700 (LWP 56467)):
[KCrash Handler]
#6  0x00007f313e1cb8db in Poppler::Page::text(QRectF const&, Poppler::Page::TextLayout) const () from /usr/lib/x86_64-linux-gnu/libpoppler-qt5.so.1
#7  0x00007f313e1cba5f in Poppler::Page::text(QRectF const&) const () from /usr/lib/x86_64-linux-gnu/libpoppler-qt5.so.1
#8  0x0000558aae771be6 in NoteIndexer::indexPdf(int) ()
#9  0x0000558aae77340e in NoteIndexer::indexResource(int) ()
#10 0x0000558aae704a6a in ResourceTable::add(int, qevercloud::Resource&, bool, int) ()
#11 0x0000558aae6f3f8d in NoteTable::add(int, qevercloud::Note const&, bool, int) ()
#12 0x0000558aae6f774e in NoteTable::sync(int, qevercloud::Note const&, int) ()
#13 0x0000558aae74ca2b in SyncRunner::syncRemoteNotes(QList<qevercloud::Note>, int) ()
#14 0x0000558aae74f2a9 in SyncRunner::processSyncChunk(qevercloud::SyncChunk&, int) ()
#15 0x0000558aae74f9e0 in SyncRunner::syncRemoteToLocal(int) ()
#16 0x0000558aae751860 in SyncRunner::evernoteSync() ()
#17 0x0000558aae751f31 in SyncRunner::synchronize() ()
#18 0x0000558aae7c2905 in ?? ()
#19 0x00007f31382c9be2 in QObject::event (this=0x558aafd04220, e=<optimized out>) at kernel/qobject.cpp:1251
#20 0x00007f313cddfe1c in QApplicationPrivate::notify_helper (this=this@entry=0x558aafc41e80, receiver=receiver@entry=0x558aafd04220, e=e@entry=0x7f311c009db0) at kernel/qapplication.cpp:3727
#21 0x00007f313cde73ef in QApplication::notify (this=0x558aafc50ff0, receiver=0x558aafd04220, e=0x7f311c009db0) at kernel/qapplication.cpp:3486
#22 0x0000558aae49cd1a in Application::notify(QObject*, QEvent*) ()
#23 0x00007f3138299fe8 in QCoreApplication::notifyInternal2 (receiver=0x558aafd04220, event=event@entry=0x7f311c009db0) at kernel/qcoreapplication.cpp:1048
#24 0x00007f313829cb2d in QCoreApplication::sendEvent (event=0x7f311c009db0, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:234
#25 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x558aafd6bd30) at kernel/qcoreapplication.cpp:1745
#26 0x00007f313829d0e8 in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1599
#27 0x00007f31382f49f3 in postEventSourceDispatch (s=0x7f30fc004ba0) at kernel/qeventdispatcher_glib.cpp:276
#28 0x00007f3130e4f387 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007f3130e4f5c0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007f3130e4f64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007f31382f402f in QEventDispatcherGlib::processEvents (this=0x7f30fc000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:422
#32 0x00007f313829830a in QEventLoop::exec (this=this@entry=0x7f310afe5ca0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:214
#33 0x00007f31380c3bba in QThread::exec (this=<optimized out>) at thread/qthread.cpp:525
#34 0x00007f31380ceadb in QThreadPrivate::start (arg=0x558aafd043b0) at thread/qthread_unix.cpp:367
#35 0x00007f31357cb6db in start_thread (arg=0x7f310afe6700) at pthread_create.c:463
#36 0x00007f31377ae88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7f310b7e7700 (LWP 56466)):
#0  0x00007f31377a1bf9 in __GI___poll (fds=0x7f3104004a70, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f3130e4f539 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f3130e4f64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f31382f404b in QEventDispatcherGlib::processEvents (this=0x7f3104000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:424
#4  0x00007f313829830a in QEventLoop::exec (this=this@entry=0x7f310b7e6ca0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:214
#5  0x00007f31380c3bba in QThread::exec (this=<optimized out>) at thread/qthread.cpp:525
#6  0x00007f31380ceadb in QThreadPrivate::start (arg=0x558aafd043d0) at thread/qthread_unix.cpp:367
#7  0x00007f31357cb6db in start_thread (arg=0x7f310b7e7700) at pthread_create.c:463
#8  0x00007f31377ae88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7f31142af700 (LWP 56465)):
#0  0x00007f3130e94c20 in g_private_get () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f3130e775f0 in g_thread_self () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f3130e4f63d in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f31382f404b in QEventDispatcherGlib::processEvents (this=0x7f310c000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:424
#4  0x00007f313829830a in QEventLoop::exec (this=this@entry=0x7f31142aec70, flags=..., flags@entry=...) at kernel/qeventloop.cpp:214
#5  0x00007f31380c3bba in QThread::exec (this=<optimized out>) at thread/qthread.cpp:525
#6  0x00007f312433ae45 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#7  0x00007f31380ceadb in QThreadPrivate::start (arg=0x7f31245b2d60) at thread/qthread_unix.cpp:367
#8  0x00007f31357cb6db in start_thread (arg=0x7f31142af700) at pthread_create.c:463
#9  0x00007f31377ae88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f3121221700 (LWP 56464)):
#0  0x00007f31377a1bf9 in __GI___poll (fds=0x7f3121220ba8, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f3129218747 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f312921a36a in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f31245f7ed9 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007f31380ceadb in QThreadPrivate::start (arg=0x558aafc9fa70) at thread/qthread_unix.cpp:367
#5  0x00007f31357cb6db in start_thread (arg=0x7f3121221700) at pthread_create.c:463
#6  0x00007f31377ae88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f312595f700 (LWP 56463)):
#0  0x00007f31357d19f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f313cc6f114) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x558aafc7c4e0, cond=0x7f313cc6f0e8) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7f313cc6f0e8, mutex=0x558aafc7c4e0) at pthread_cond_wait.c:655
#3  0x00007f3137d4d79c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f313bf81217 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#5  0x00007f313bf81359 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#6  0x00007f3137d5357f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f31357cb6db in start_thread (arg=0x7f312595f700) at pthread_create.c:463
#8  0x00007f31377ae88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f313e5b0900 (LWP 56462)):
#0  0x00007f313779d0b4 in __GI___libc_read (fd=5, buf=0x7fff7cda1160, nbytes=16) at ../sysdeps/unix/sysv/linux/read.c:27
#1  0x00007f3130e93cd0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f3130e4f027 in g_main_context_check () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f3130e4f4e0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f3130e4f64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f31382f404b in QEventDispatcherGlib::processEvents (this=0x558aafcdf2e0, flags=...) at kernel/qeventdispatcher_glib.cpp:424
#6  0x00007f3124683761 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#7  0x00007f313829830a in QEventLoop::exec (this=this@entry=0x7fff7cda1390, flags=..., flags@entry=...) at kernel/qeventloop.cpp:214
#8  0x00007f31382a14d0 in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1336
#9  0x0000558aae498a8b in main ()

[messages.zip](https://github.com/robert7/nixnote2/files/2715611/messages.zip)

**Comment by robert7** [comment]
hi
from the log: "Resource not found for lid:22993 key:6003 hash" ... you seem to have one or more notes with missing resources.
Further the messages: 
"Error: Couldn't find trailer dictionary"
"Error: Invalid XRef entry"
Seem to be related to PDF rendering. So it could be corrupted PDF attachment.

If you can identify unsynced notes, delete them (you can copy the content away by copy/paste e.g. to text editor). After deleting unsynced notes, try to sync.

In case it doesn't work, there is always the "brute force" option. Backup your local data away (where it is stored: see menu Help/Data and log location info). Then delete the local data and try sync from scratch. Note that if you have many notes, this may take long time - e.g. let it run over night.
