### ISSUE TITLE
Sync error with "col" Tag

### ISSUE THREAD

**Issue by kaiching0108** [robert7/nixnote2#74]
nixnote2 Version: 2.1.2-e-126d240 (AppImage)
 
I switch from ver.2.0.2 to 2.1.2-e and got some sync error message:

ERROR 2018-12-31 06:20:26.350 src/communication/communicationmanager.cpp:504 Exception stacktrace:
ERROR 2018-12-31 06:20:26.354 src/communication/communicationerror.cpp:86 "EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=The end-tag for element type \"col\" must end with a '>' delimiter."

it seems an old bug:
https://github.com/baumgarr/nixnote2/issues/385

by the way, i can't type in chinese in nixnote2, any config should i setup first?

**Comment by robert7** [comment]
hi,
short ago I fixed error related to invalid HTML markup for tables created in nixnote (see https://github.com/robert7/nixnote2/issues/27). This fix was made in v. 2.1.0-beta4h so it is already included in 2.1.2-e.

I tried currently (with 2.1.2-f) to create one table in nixnote and other table in evernote webclient. Both seems to work fine. There are no sync errors. 

![screen_20181231_05](https://user-images.githubusercontent.com/1135218/50558665-779d6980-0cf0-11e9-83c0-712d09b097f7.png)

It could be you someway already have erroneous markup which someway fails to be cleaned up with "tidy". Can you reproduce the problems with new note? Can you describe steps for reproduction? 

If it is just one case/one time issue, then you can fix the markup manually e.g. by editing HTML and e.g. by removing the offending "<col>" tag. You can edit HTML selecting "View/Show source". Or copy the content to clipboard, then delete the note and insert it in evernote web client.

I believe the old bug https://github.com/baumgarr/nixnote2/issues/385 is already fixed (by using new html tidy).

>by the way, i can't type in chinese in nixnote2, any config should i setup first?

Unfortunately I don't speak/can't type Chinese, so its difficult to help you with that. I have no idea how the Chinese characters are typed in.
This issue: https://github.com/baumgarr/nixnote2/issues/430#issuecomment-447844912 could be related.
Further it could be issue of the AppImage as it uses older Qt 5.5. Can you someway try the Ubuntu version from the PPA? whenever you can reproduce the problem with chinese letters with the PPA version. The PPA version is using newer Qt version (system default). You could try e.g. by booting Ubuntu 18.04 live CD, install PPA version and try. PPA: https://github.com/robert7/nixnote2#ubuntu

**Comment by kaiching0108** [comment]
Dear robert7:
thank you for reply.
After following your suggestion to edit the HTML code, the sync function seems work with no error now.(thanks~)
I have tried install nixnote2 from PPA, but nixnote2 still no response to my fcitx input method framework.(I can't use Ctrl+space to switch input method from english to chinese)

**Comment by robert7** [comment]
great!
