### ISSUE TITLE
Focus on New Note does not work if Note is created directly after starting Nixnote

### ISSUE THREAD

**Issue by stemabu** [robert7/nixnote2#77]
## Expected vs. actual behavior
Focus of editing should be in title of new created note. Instead, the first "old" note title is highlighted for editing.

## Steps to reproduce the problem
  1. Start Nixnote
  2. Press "New Note" button without doing any editing or searching before

As soon as there is any searching or editing – or from creating the second new note of the session – the behavior is as expected, i.e. focus is in highlighted title of new note.

**Comment by robert7** [comment]
OK. I already noticed. I'll fix it

**Comment by robert7** [comment]
@stemabu should be fixed in version 2.1.3-e
