### ISSUE TITLE
Clicking on tray icon does not create a new note, or show/hide when configured to do so.

### ISSUE THREAD

**Issue by timoc** [robert7/nixnote2#8]
It does not respond to any click configured operations.

**Comment by robert7** [comment]
Hm. Yes I know this. This doesn't work. I already looked at it. Currently no idea how to fix. May be someway connected to used Qt version (AppImage version currently uses 5.5.1). 

I'll look at it.

**Comment by robert7** [comment]
I'll looked at it, but unfortunately so far can't figure out why it does not work. Funny that in 2.0.2 it works and the code is basically the same here - but the tray icon doesn't get the "activated" signal. No idea..

But I have something better (system wide global keyboard shortcuts).. I'll describe later..

**Comment by timoc** [comment]
I have a reference for that, I was thkinking about having a crack at integrating JSrobokey to help automate capture and manage templates.

**Comment by robert7** [comment]
So here is a [tutorial how to add global keyboard shortcuts](https://nixnotes-21.blogspot.com/2018/08/nixnote-global-keyboard-shortcuts.html) - which may be quicker then mouse clicks on system tray.

I'll will still let this issue open, as I would like to fix the systray problem, but for now I have no idea why it doesn't work..

**Comment by SaurabhMhaisekar** [comment]
This is strange, this works in weird way, it does create a new note named untitled note in the note that was selected by user but does not show any dialog or any confirmation that it created a note. Maybe a better idea would be create a new window for creating new note.

**Comment by robert7** [comment]
@SaurabhMhaisekar I fixed this in v. 2.1.0-beta4d - pls recheck

**Comment by robert7** [comment]
@timoc and I was finally able to fix the original issue - so middle click and double click can now be configured (standard click doesn't work, as this shows tray menu itself)
pls retest in v. 2.1.0-beta4d

**Comment by SaurabhMhaisekar** [comment]
@robert7 seems to work fine now.
