### ISSUE TITLE
Sync Errors on startup

### ISSUE THREAD

**Issue by kendoori** [robert7/nixnote2#80]
I keep getting sync errors on startup. When I look in the log I see this.

`ERROR 2019-01-31 21:17:44.784 src/communication/communicationerror.cpp:86 "EDAMUserException[PERMISSION_DENIED]: EDAMUserException: PERMISSION_DENIED parameter=authenticationToken"`

I deauthorized, restarted and reauthorized.

I am running:
Version: 201901281531~2.1.3-c~ubuntu18.04.1 on Mint 19.1

**Comment by robert7** [comment]
Authentication token is stored in "accounts.conf" in "config directory" (e.g. `/home/robert7/.nixnote/accounts.conf` - which one it is on your system, you can find out by going to "Help/Data and log location info".

It could be the file is corrupted or there is some access error.

What you could try is to start from scratch by setting "configDir" to a new directory, where you have write access. E.g. `nixnote2 --logLevel=1 --configDir=/home/xy/.nixnote-new`.

If it doesn't work, you can try to post the newly created log file (should be in `/home/xy/.nixnote-new/log-1`).

**Comment by kendoori** [comment]
[messages.log](https://github.com/robert7/nixnote2/files/2833817/messages.log)

**Comment by robert7** [comment]
@kendoori 
I looked at the log, but did you tried sync?
because what I see in log, you just started the app and then terminated it..

**Comment by robert7** [comment]
if you still have the problem, then pls provide more info (e.g. DEBUG level log file where the sync is present)
