### ISSUE TITLE
Entering coordinates doesn't work

### ISSUE THREAD

**Issue by Discostu36** [robert7/nixnote2#81]
## Expected vs. actual behavior
Expected:
- To add a location to a note I can enter the coordinates with decimal point or a decimal comma and it will be saved

Actual:
- I can't enter a decimal point in the coordinates. I can enter them with a decimal comma, but they are not saved.

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))
[messages.log](https://github.com/robert7/nixnote2/files/2823563/messages.log)

  1. Select a note
  2. Click on "Klicke um die Position festzulegen" (don't know the English string)
  3. Try to enter coordinates with decimal point
  4. Enter coordinates with decimal comma
  5. Click "OK"

## Specifications

  - [Version](https://github.com/robert7/nixnote2/wiki/HowTo---Check-used-application-version):  2.1.1-0.1~mx17+1
- German language version on a German system (decimal comma is the right choice here)

**Comment by robert7** [comment]
ok. it doesn't seem to work on english version too... I'll check it later

**Comment by robert7** [comment]
It should be fixed from version 2.1.3-i

![screen_20190313_01](https://user-images.githubusercontent.com/1135218/54261592-74ceb880-456c-11e9-8cb4-8bc9f44eec84.png)

![screen_20190313_02](https://user-images.githubusercontent.com/1135218/54261596-77c9a900-456c-11e9-8253-4d8fc4000f48.png)

![screen_20190313_03](https://user-images.githubusercontent.com/1135218/54261602-79936c80-456c-11e9-95f8-4a8c1323343e.png)

**Comment by robert7** [comment]
I did some tests with Ubuntu set to german. It seems, you need to enter the coordinates with decimal point not a comma. If you enter the number it bad format, it will be ignored and set to "0.0".

![screen_20190313_04](https://user-images.githubusercontent.com/1135218/54262239-02f76e80-456e-11e9-9c32-c114e57f0b49.png)
