### ISSUE TITLE
the note will auto disable editing after i edit source?

### ISSUE THREAD

**Issue by kaiching0108** [robert7/nixnote2#83]
## Expected vs. actual behavior

i copied the note's source to external editor (like Lefpad) to edit.
after i paste back to the note, the note will disable editing. how to fix this?

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))

  1. open a note-A
  2. view > show source
  3. copy note-A's source to Leafpad to edit.
  4. paste the source back to note-A
  5. note-A auto disable editing

## Specifications

  - Version: 201901281531~2.1.3-c~ubuntu18.04.1

**Comment by robert7** [comment]
Normally HTML editing should work and should not set the note to "read only" (doesn't matter if you edit in place or copy/past html from other source).

Read-only flag is set, in few specific circumstances where some internal mismatch is found. E.g. reference to non existing resources (e.g. attachment images). Usually you can find more info in log - what was the cause.
