### ISSUE TITLE
Real Note Links ( not In-App Links)

### ISSUE THREAD

**Issue by mickmattes** [robert7/nixnote2#84]
Hi, 

maybe I'm missing some information but for me it looks like there is no way to get a "Public" or "Note Link" from the notes in Nixnote2. When right clicking on a note, I can chose "Copy Note Link", but this gives me a link of the form:
`evernote:///view/.....`
What I want is something of the form:
`https://www.evernote.com/shard/...`
According to this site: [Evernote Developers](https://dev.evernote.com/doc/articles/note_links.php), the name "Note Link" is not used correctly in Nixnote2.

Background:
I use Todoist and I want to insert links to notes, so that a browser (or even Nixnote2) would open up and show me the note, when I click on it. With In-App Notes, this is not possible (as far as I know).

Thanks in advance!

**Comment by robert7** [comment]
ok it could be nice improvement and you be easy to implement
sorry currently I'm bit out of time, so I mainly doing basic maintenance and bugs
but pull requests are always welcome :)

**Comment by robert7** [comment]
@mickmattes 
So I added the feature and renamed the existing "Note Links" to "In-App Note Links".
Currently its only available in "Note List" (not yet in Note Editor).
Its available from version 2.1.3-f

**Comment by mickmattes** [comment]
@robert7  
You are the best! Thank you very much for that fast support!

**Comment by robert7** [comment]
i had a bit time yesterday and the link you provided, was great help
i think its nice little feature

I also considering adding a context menu option "Open in web client" which is basically just open web browser with the "Note Link" - this also may be useful sometimes

**Comment by grand-lotus-iroh** [comment]
How do I request an updated Fedora build? https://github.com/robert7/nixnote2#fedora

I installed nix, and was hoping for this feature. It turns out I'm using version 2.1.2 on Fedora 29, but when I visit the copr build page, it looks like it's not updated to  version 2.1.3-f -- https://copr.fedorainfracloud.org/coprs/nunodias/nixnote2/builds/

Is this something I could just request someone else to deploy? Not sure how this works, maybe you are owner of the copr build and need to manually update for community? Perhaps I'd be better off just manually building this myself?

Any input would be nice, thanks for everything - love niixnote2!

**Comment by robert7** [comment]
@grand-lotus-iroh: sorry no Idea.. you need to contact the maintainer of the packaging
Unfortunately here I don't have any contact.
If you found out the contact, the pls let me know

**Comment by grand-lotus-iroh** [comment]
Found a helpful page here: https://github.com/robert7/nixnote2/wiki/HowTo---Run-AppImage

It looks like I can just download the NixNote2-x86_64.AppImage from [Release Page](https://github.com/robert7/nixnote2/releases) and just double click.

Thanks for rapid response and have good day buddy. Best of luck.

**Comment by robert7** [comment]
@grand-lotus-iroh yes of course, the AppImage version should work out-of-the-box for all distributions.

**Comment by ndias** [comment]
Here, you can request here :)
 
 I will try to update to the new version today!

Cheers,
Nuno

On Mon, 2019-04-29 at 18:04 +0000, Uncle Iroh wrote:
> How do I request an updated Fedora build? 
> https://github.com/robert7/nixnote2#fedora
> I installed nix, and was hoping for this feature. It turns out I'm
> using version 2.1.2 on Fedora 29, but when I visit the copr build
> page, it looks like it's not updated to version 2.1.3-f -- 
> https://copr.fedorainfracloud.org/coprs/nunodias/nixnote2/builds/
> Is this something I could just request someone else to deploy? Not
> sure how this works, maybe you are owner of the copr build and need
> to manually update for community? Perhaps I'd be better off just
> manually building this myself?
> Any input would be nice, thanks for everything - love niixnote2!
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
Nuno Dias <Nuno.Dias@gmail.com>

**Comment by ndias** [comment]
@grand-lotus-iroh 
New rpm version available

If not showed, try a 
$ dnf clean all

**Comment by grand-lotus-iroh** [comment]
Brilliant! Thanks for the added effort and update.

Hey @robert7 -- is this a good thread to request another similar feature? If so, I'd like to request "_Copy Public Note Link_" so people are not required to log into Evernote. Here is a note example:
* [login required](https://www.evernote.com/shard/s207/nl/26794033/3927348b-bee6-4638-8608-6e0b0dd2edde/)
* [login note required](https://www.evernote.com/shard/s207/sh/5af45638-e0f5-44d2-8331-05affe158715/b37e6d65711d7ce01e14ac44dafdba91)

Right now, a user has to log into web client to make note public:
![share-note-public](https://user-images.githubusercontent.com/1291364/56982265-e8457d00-6b4e-11e9-8e3a-56e12a210d5b.gif)
