### ISSUE TITLE
New Window

### ISSUE THREAD

**Issue by krolloc1** [robert7/nixnote2#86]
I use evernote for both work and home using two different accounts. I work from home a lot andit would be nice if I could have one window open for work and one window open for home. Would that be possible?

I appreciate the work you do on this.

**Comment by robert7** [comment]
Hi,
this is easily possible. You just need to run the second instance with different config and data directory.. Example on your home computer start the second instance as `nixnote --configDir=/home/xy/.nixnote-work` this will create second config/data dir, which you need to sync first. But then, you can use both at the same time. Drawback is, that you will have 2x same icon in systray - but if you consistently start the instances in same order, you will learn that the e.g. first is work and second is private.

I'm too using Evernote for both work & private, but just with one account using 2 different notebooks. But it depends whats better for you.

More info on wiki page: https://github.com/robert7/nixnote2/wiki/Relocation-of-config-and-data-directory

**Comment by krolloc1** [comment]
Thank you very much for tht information. I will try it today.
