### ISSUE TITLE
Syncing fails

### ISSUE THREAD

**Issue by Twoflower2** [robert7/nixnote2#87]
See the attached log files. (I did debug and trace level logging. See messages_debug.log and messages_trace.log)
[logs-1.tar.gz](https://github.com/robert7/nixnote2/files/2854713/logs-1.tar.gz)

**Comment by robert7** [comment]
ok i'll recheck the validation
the relevant message is `"EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=Attribute \"class\" must be declared for element type \"h2\"."`

so there is <h2> tag with "class" attribute
normally the cleanup should delete the offending attribute (as it is not relevant to be stored in note and its forbidden in evernote)

was the html content pasted from a web page? if yes, then maybe its good idea to try the "evernote web clipper" - can be installed e.g. as extension in chrome. this will upload the selected text from webpage as new note and after sync you can edit in nixnote

but in case I can confirm the problem with the "h2", i'll fix it

**Comment by Twoflower2** [comment]
Yes the page was pasted. I now use KDE's Falkon and it has very little extensions and I'm sure not Evernote Web clipper. I'll look for different options.

**Comment by robert7** [comment]
i'll check the problem with the "class" attribute later. I know about one more similar problem (when "a" tag has id but no "href").
In most cases the existing cleanup should already work fine.

Alternative workaround to web clipper is simply open web client and manually paste the content there as new note. Then you can edit in NN.

**Comment by robert7** [comment]
@Twoflower2 
the logs you provided, were of great help, but `files` directory you provided, only contained data for `messages_trace.log` as the `files` directory is deleted after application startup.
The log shown various kind of sync error - which was quite surprising for me.

I was able to identify one general problem in the html markup cleanup, which could be source of all problems. Please retry with the new development version (2.1.3-g) and let me know, if you can find any more cases where it doesn't work. In this case contents of the `files` directory would be really helpful (DEBUG level logging is enough).


----------
present errors
`messages.log:ERROR 2019-02-12 09:01:53.122 src/communication/communicationerror.cpp:86 "EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=Element type \"fieldset\" must be declared."
messages.log:ERROR 2019-02-12 09:01:53.974 src/communication/communicationerror.cpp:86 "EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=Attribute \"type\" is required and must be specified for element type \"en-media\"."
messages.log:ERROR 2019-02-12 09:01:54.213 src/communication/communicationerror.cpp:86 "EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=Attribute \"class\" must be declared for element type \"h2\"."
messages.log:ERROR 2019-02-12 09:01:54.444 src/communication/communicationerror.cpp:86 "EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=The element type \"hr\" must be terminated by the matching end-tag \"</hr>\"."
messages_debug.log:ERROR 2019-02-12 08:58:30.764 src/communication/communicationerror.cpp:86 "EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=Element type \"fieldset\" must be declared."
messages_debug.log:ERROR 2019-02-12 08:58:31.618 src/communication/communicationerror.cpp:86 "EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=Attribute \"type\" is required and must be specified for element type \"en-media\"."
messages_debug.log:ERROR 2019-02-12 08:58:31.856 src/communication/communicationerror.cpp:86 "EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=Attribute \"class\" must be declared for element type \"h2\"."
messages_debug.log:ERROR 2019-02-12 08:58:32.085 src/communication/communicationerror.cpp:86 "EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=The element type \"hr\" must be terminated by the matching end-tag \"</hr>\"."
messages_trace.log:ERROR 2019-02-12 09:01:53.122 src/communication/communicationerror.cpp:86 "EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=Element type \"fieldset\" must be declared."
messages_trace.log:ERROR 2019-02-12 09:01:53.974 src/communication/communicationerror.cpp:86 "EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=Attribute \"type\" is required and must be specified for element type \"en-media\"."
messages_trace.log:ERROR 2019-02-12 09:01:54.213 src/communication/communicationerror.cpp:86 "EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=Attribute \"class\" must be declared for element type \"h2\"."
messages_trace.log:ERROR 2019-02-12 09:01:54.444 src/communication/communicationerror.cpp:86 "EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=The element type \"hr\" must be terminated by the matching end-tag \"</hr>\"."
`

**Comment by robert7** [comment]
I'm closing this; let me know/reopen if yuo find any more SYNC issues
