### ISSUE TITLE
PDF dissapears if modified with inline PDF on

### ISSUE THREAD

**Issue by Germanc** [robert7/nixnote2#90]
If I activate 'Display PDFs inline', open the pdf, edit it (annotate/highlight), save as the same file and sync, the pdf file can no longer be accessed outside of nixnote2. Without 'Display PDFs inline' I can annotate the pdf file and sync and it syncs correctly.

**Comment by robert7** [comment]
hi,
I looked up the problem and basically what you are trying to do isn't supported use case. So its not really a bug, but a feature :) 

If you open attachment in external application (e.g. a PDF attachment) and you edit it, Nixnote doesn't detect, that you changed the file. The file is opened directly with Nixnote local storage, so if you change the file, you locally see it in Nixnote as updated. But as Nixnote **din't really detected you changed the attachment - it will not be synced to Evernote**. So after e.g. losing the local data, you'll find original PDF copy in the cloud (so you lose your annotations!).
This doesn't depend whenever you display PDFs inline or nor.

The correct way would be reattach the PDF after editing it. Which is course a bit tedious.

But I found some additional problem with syncing PDFs, so I will look this a bit further later. Maybe I can find some easy workaround.

**Comment by Germanc** [comment]
Hi,
That's weird. The annotations are getting synced, I can see them in the web app and mobile app. I even reported a bug for a similar issue to the original developer and it was working (https://github.com/baumgarr/nixnote2/issues/206). If it's not a supported use case I will not use it, in case it fails.
