### ISSUE TITLE
Shortcut for "ToDo" checkbox

### ISSUE THREAD

**Issue by AiratHalitov** [robert7/nixnote2#92]
Hi! Thanks for your updates!

Can you add "`Ctrl+Shift+C`" as shortcut for "ToDo" checkbox by default? 

  - Version: `201901281531~2.1.3-c~ubuntu16.04.1`

**Comment by robert7** [comment]
Hi
it will be available from version 2.1.3-h (which will be build shortly).
anyway you can easily customize the shortcuts yourself. Create `shortcuts.txt` in the config directory - e.g. in `~/.nixnote`, then put there just the lines you want changed. This will persist between updates..

More info: https://github.com/robert7/nixnote2/wiki/HowTo---Customize-keyboard-shortcuts

**Comment by AiratHalitov** [comment]
You mean `~/.config/nixnote2` folder

**Comment by robert7** [comment]
>You mean ~/.config/nixnote2 folder

this depends which directory are you using for config (you can find it out in `Help/Data and log location info`).
Legacy installations are using `~/.nixnote` new should use `~/.config/nixnote2`. But you can also change it manually using `--configDir` command line option.

**Comment by AiratHalitov** [comment]
I'm using new installation and `~/.config/nixnote2` folder.
Thanks!
