### ISSUE TITLE
Appending to todo lists in editor

### ISSUE THREAD

**Issue by kgolding** [robert7/nixnote2#93]
Is it possible to have the editor treat the todo checkbox as a list bullet, so a new todo is added after pressing enter?

**Comment by robert7** [comment]
if you first insert a bulleted list (see screenshoot)
the press Ctrl-Shift-C on each line, then it should do exactly that.
![screen_20190320_02](https://user-images.githubusercontent.com/1135218/54667039-b078fd80-4aeb-11e9-8759-f33caec80ba1.png)

or the same with numbered list
![screen_20190320_03](https://user-images.githubusercontent.com/1135218/54667072-c38bcd80-4aeb-11e9-9aae-a66bf75a6917.png)

**Comment by kgolding** [comment]
Thanks.
