### ISSUE TITLE
Sync issues with tables

### ISSUE THREAD

**Issue by epic9x** [robert7/nixnote2#94]
## Expected vs. actual behavior
Notes with tables should sync, but fail to do so and produce errors.  

```
 ERROR 2019-03-20 03:06:42.713 ( communication/communicationmanager.cpp @ 561 ) EDAMUserException: 11 
ERROR 2019-03-20 03:06:42.713 ( threads/syncrunner.cpp @ 1188 ) "Error uploading note:Test Note" 
ERROR 2019-03-20 03:06:42.714 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
 INFO 2019-03-20 03:06:42.714 ( nixnote.cpp @ 1900 ) "Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Element type \"table\" must be followed by either attribute specifications, \">\" or \"/>\"." 
```
This may be a second issue, but I also have one note that also produces this error with the following:
```
ERROR 2019-03-20 03:22:09.383 ( sql/tagtable.cpp @ 395 ) Unknown Tag record key: 1004 
ERROR 2019-03-20 03:22:09.521 ( communication/communicationmanager.cpp @ 561 ) EDAMUserException: 11 
ERROR 2019-03-20 03:22:09.521 ( threads/syncrunner.cpp @ 1188 ) "Error uploading note:REDACTED NOTE TITLE" 
 INFO 2019-03-20 03:22:09.523 ( nixnote.cpp @ 1900 ) "Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=The end-tag for element type \"col\" must end with a '>' delimiter." 
```

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))

  1. create note
  1. add a two column table with content in the each field
  1. attempt to sync and see errors

## Specifications

  - 2.02 on ubuntu 18.04
  - 2.1.2 appImage release on 18.04

**Comment by robert7** [comment]
Hi
I just tried exactly the steps with the current version (2.1.3-i) and I can't reproduce.
Please try with the development version https://github.com/robert7/nixnote2/releases/tag/continuous-develop and if you can reproduce, then attach log file incl. "files" folder - you can try to reproduce with test account and test data, so no private data will be visible in logs.
Either use the last AppImage (2.1.3-i) or install from development PPA.

freshly created table & synced OK:
![screen_20190320_01](https://user-images.githubusercontent.com/1135218/54666782-06997100-4aeb-11e9-97c4-735aacedb3e5.png)
