### ISSUE TITLE
Double Click on Tray Doesn't Restore NixNote

### ISSUE THREAD

**Issue by kendoori** [robert7/nixnote2#97]
## Expected vs. actual behavior

In spite of having set the preference to double click icon to show NixNote, double click shows a context menu, not the interface.

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))

  1. Set preference Tray Icon Double Click Action = Show NixNote
  2. Double click on tray. 
  3. Context menu is shown.

## Specifications

  - [Version](https://github.com/robert7/nixnote2/wiki/HowTo---Check-used-application-version):
I have Version: 201904050846~2.1.3~ubuntu18.04.1 on Linux Mint 19.1 Cinnamon.

**Comment by robert7** [comment]
hmm no idea as it works for me on Ubuntu 18.04
you can try to start nixnote with debug logging `nixnote2 --logLevel=1`
then close it to tray, then try double click and post the last log lines - on my computer it prints:

![screen_20190417_09](https://user-images.githubusercontent.com/1135218/56279596-b7098d80-6108-11e9-9401-20f82288a406.png)

as alternative, which I personally find better the double clicking the systray is a global keyboard shortcut
which is actually faster
https://github.com/robert7/nixnote2/wiki/System-wide-global-keyboard-shortcuts

e.g. I have Window+N key to show nixnote and it works quite stable
