### ISSUE TITLE
cursor movements around "ToDo" checkbox

### ISSUE THREAD

**Issue by lisaak1** [robert7/nixnote2#99]
## Expected vs. actual behavior
Cursor is displayed in front of ToDo checkbox even when it's position is behind it. It's a little bit confusing, esp. when you want to press delete or backspace - you never know where is really the cursor and what char will be deleted. 
Luckilly you don't need usually three checkboxes in row, because when you try the cursor behavior with 3 boxes in line, you could become mad of it. :-)

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))

  1. add checkbox
  2. add text after it in the same line
  3. try to go back using cursor keys and place cursor between first char and checkbox

## Specifications
Version: 2.1.2-1
Debian Buster 
package from official repository

**Comment by robert7** [comment]
hi,
I see it works like you described... But unfortunately it seems to be how the used HTML editor handles the markup. And I don't see any easy way how to influence it.
The used html editor comes from Qt webkit which is obsolete and the new one is Qt webengine - unfortunately the port is far from easy and I don't currently have time to do it.

So currently unfortunately its a feature not a bug...
Get accustomed to the behavior :D
It just an visual "glitch"

![screen_20190417_08](https://user-images.githubusercontent.com/1135218/56278608-d3a4c600-6106-11e9-8901-3b2290e7066f.png)
